---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[威武极天战士21]],
		["pos_x"]=20,
		["pos_y"]=79,
		["num"]=1,
		["range"]=0, 
	},
	[2] = {
 		["key_name"]=2,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[威武极天战士31]],
		["pos_x"]=81,
		["pos_y"]=80,
		["num"]=1,
		["range"]=0, 
	},
	[3] = {
 		["key_name"]=3,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[威武极天战士41]],
		["pos_x"]=77,
		["pos_y"]=22,
		["num"]=1,
		["range"]=0, 
	},
	[4] = {
 		["key_name"]=4,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[爆不爆谁知道1]],
		["pos_x"]=37,
		["pos_y"]=35,
		["num"]=1,
		["range"]=0, 
	},
	[5] = {
 		["key_name"]=5,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[热血牛魔王1]],
		["pos_x"]=24,
		["pos_y"]=27,
		["num"]=1,
		["range"]=0, 
		["color"]=249, 
	},
	[6] = {
 		["key_name"]=6,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[热血虹魔教主1]],
		["pos_x"]=21,
		["pos_y"]=24,
		["num"]=1,
		["range"]=0, 
		["color"]=249, 
	},
	[7] = {
 		["key_name"]=7,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[热血沃玛教主1]],
		["pos_x"]=20,
		["pos_y"]=20,
		["num"]=1,
		["range"]=0, 
		["color"]=249, 
	},
	[8] = {
 		["key_name"]=8,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[热血祖玛教主1]],
		["pos_x"]=24,
		["pos_y"]=18,
		["num"]=1,
		["range"]=0, 
		["color"]=249, 
	},
	[9] = {
 		["key_name"]=9,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[热血魔龙教主1]],
		["pos_x"]=26,
		["pos_y"]=21,
		["num"]=1,
		["range"]=0, 
		["color"]=249, 
	},
	[10] = {
 		["key_name"]=10,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[热血雪域魔王1]],
		["pos_x"]=29,
		["pos_y"]=22,
		["num"]=1,
		["range"]=0, 
		["color"]=249, 
	},
	[11] = {
 		["key_name"]=11,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[狂热双头金刚1]],
		["pos_x"]=23,
		["pos_y"]=21,
		["num"]=1,
		["range"]=0,
		["color"]=249,  
	},
	[12] = {
 		["key_name"]=12,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[狂热双头血魔1]],
		["pos_x"]=27,
		["pos_y"]=25,
		["num"]=1,
		["range"]=0, 
		["color"]=249, 
	},
	[13] = {
 		["key_name"]=13,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古双头血魔1]],
		["pos_x"]=14,
		["pos_y"]=57,
		["num"]=1,
		["range"]=0, 
	},
	[14] = {
 		["key_name"]=14,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古双头金刚1]],
		["pos_x"]=41,
		["pos_y"]=84,
		["num"]=1,
		["range"]=0, 
	},
	[15] = {
 		["key_name"]=15,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古沃玛教主1]],
		["pos_x"]=65,
		["pos_y"]=80,
		["num"]=1,
		["range"]=0, 
	},
	[16] = {
 		["key_name"]=16,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古祖玛教主1]],
		["pos_x"]=54,
		["pos_y"]=62,
		["num"]=1,
		["range"]=0, 
	},
	[17] = {
 		["key_name"]=17,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古虹魔教主1]],
		["pos_x"]=39,
		["pos_y"]=47,
		["num"]=1,
		["range"]=0, 
	},
	[18] = {
 		["key_name"]=18,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古牛魔王1]],
		["pos_x"]=29,
		["pos_y"]=17,
		["num"]=1,
		["range"]=0, 
	},
	[19] = {
 		["key_name"]=19,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古魔龙教主1]],
		["pos_x"]=55,
		["pos_y"]=25,
		["num"]=1,
		["range"]=0, 
	},
	[20] = {
 		["key_name"]=20,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古雪域魔王1]],
		["pos_x"]=85,
		["pos_y"]=24,
		["num"]=1,
		["range"]=0, 
	},
	[21] = {
 		["key_name"]=21,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[贞子1]],
		["pos_x"]=24,
		["pos_y"]=19,
		["num"]=60,
		["range"]=6, 
	},
	[22] = {
 		["key_name"]=22,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[幽灵1]],
		["pos_x"]=24,
		["pos_y"]=26,
		["num"]=60,
		["range"]=6, 
	},  
}
 return config;