---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[威武极天战士1]],
		["pos_x"]=27,
		["pos_y"]=21,
		["num"]=1,
		["range"]=0, 
	},
	[2] = {
 		["key_name"]=2,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[威武极天战士2]],
		["pos_x"]=20,
		["pos_y"]=79,
		["num"]=1,
		["range"]=0, 
	},
	[3] = {
 		["key_name"]=3,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[威武极天战士3]],
		["pos_x"]=81,
		["pos_y"]=80,
		["num"]=1,
		["range"]=0, 
	},
	[4] = {
 		["key_name"]=4,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[威武极天战士4]],
		["pos_x"]=77,
		["pos_y"]=22,
		["num"]=1,
		["range"]=0, 
	},
	[5] = {
 		["key_name"]=5,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[爆不爆谁知道]],
		["pos_x"]=37,
		["pos_y"]=35,
		["num"]=1,
		["range"]=0, 
	},
	[6] = {
 		["key_name"]=6,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古双头血魔]],
		["pos_x"]=14,
		["pos_y"]=57,
		["num"]=1,
		["range"]=0, 
	},
	[7] = {
 		["key_name"]=7,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古双头金刚]],
		["pos_x"]=41,
		["pos_y"]=84,
		["num"]=1,
		["range"]=0, 
	},
	[8] = {
 		["key_name"]=8,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古沃玛教主]],
		["pos_x"]=65,
		["pos_y"]=80,
		["num"]=1,
		["range"]=0, 
	},
	[9] = {
 		["key_name"]=9,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古祖玛教主]],
		["pos_x"]=54,
		["pos_y"]=62,
		["num"]=1,
		["range"]=0, 
	},
	[10] = {
 		["key_name"]=10,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古虹魔教主]],
		["pos_x"]=39,
		["pos_y"]=47,
		["num"]=1,
		["range"]=0, 
	},
	[11] = {
 		["key_name"]=11,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古牛魔王]],
		["pos_x"]=29,
		["pos_y"]=17,
		["num"]=1,
		["range"]=0, 
	},
	[12] = {
 		["key_name"]=12,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古魔龙教主]],
		["pos_x"]=55,
		["pos_y"]=25,
		["num"]=1,
		["range"]=0, 
	},
	[13] = {
 		["key_name"]=13,
		["map_id"]=[[诡异空间二层]],
		["mon_name"]=[[复古雪域魔王]],
		["pos_x"]=85,
		["pos_y"]=24,
		["num"]=1,
		["range"]=0, 
	},
	[14] = {
 		["key_name"]=14,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[贞子]],
		["pos_x"]=24,
		["pos_y"]=19,
		["num"]=15,
		["range"]=6, 
	},
	[15] = {
 		["key_name"]=15,
		["map_id"]=[[诡异空间一层]],
		["mon_name"]=[[幽灵]],
		["pos_x"]=24,
		["pos_y"]=26,
		["num"]=15,
		["range"]=6, 
	},  
}
 return config;