---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["name"]=[[开天]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[2] = {
 		["key_name"]=2,
		["name"]=[[奔雷战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[3] = {
 		["key_name"]=3,
		["name"]=[[奔雷战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[4] = {
 		["key_name"]=4,
		["name"]=[[奔雷项链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[5] = {
 		["key_name"]=5,
		["name"]=[[奔雷护腕]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[6] = {
 		["key_name"]=6,
		["name"]=[[奔雷战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[7] = {
 		["key_name"]=7,
		["name"]=[[奔雷腰带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[8] = {
 		["key_name"]=8,
		["name"]=[[奔雷战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[9] = {
 		["key_name"]=9,
		["name"]=[[镇天]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[10] = {
 		["key_name"]=10,
		["name"]=[[怒焰魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[11] = {
 		["key_name"]=11,
		["name"]=[[怒焰魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[12] = {
 		["key_name"]=12,
		["name"]=[[怒焰项链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[13] = {
 		["key_name"]=13,
		["name"]=[[怒焰护腕]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[14] = {
 		["key_name"]=14,
		["name"]=[[怒焰魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[15] = {
 		["key_name"]=15,
		["name"]=[[怒焰腰带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[16] = {
 		["key_name"]=16,
		["name"]=[[怒焰魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[17] = {
 		["key_name"]=17,
		["name"]=[[玄天]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[18] = {
 		["key_name"]=18,
		["name"]=[[极光道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[19] = {
 		["key_name"]=19,
		["name"]=[[极光道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[20] = {
 		["key_name"]=20,
		["name"]=[[极光项链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[21] = {
 		["key_name"]=21,
		["name"]=[[极光护腕]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[22] = {
 		["key_name"]=22,
		["name"]=[[极光道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[23] = {
 		["key_name"]=23,
		["name"]=[[极光腰带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[24] = {
 		["key_name"]=24,
		["name"]=[[极光道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=150, 
	},
	[25] = {
 		["key_name"]=25,
		["name"]=[[祖玛裁决]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[26] = {
 		["key_name"]=26,
		["name"]=[[虎啸战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[27] = {
 		["key_name"]=27,
		["name"]=[[虎啸战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[28] = {
 		["key_name"]=28,
		["name"]=[[虎啸战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[29] = {
 		["key_name"]=29,
		["name"]=[[虎啸战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[30] = {
 		["key_name"]=30,
		["name"]=[[虎啸战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[31] = {
 		["key_name"]=31,
		["name"]=[[虎啸战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[32] = {
 		["key_name"]=32,
		["name"]=[[虎啸战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[33] = {
 		["key_name"]=33,
		["name"]=[[虎啸战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[34] = {
 		["key_name"]=34,
		["name"]=[[祖玛骨玉]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[35] = {
 		["key_name"]=35,
		["name"]=[[聚魔法衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[36] = {
 		["key_name"]=36,
		["name"]=[[聚魔法衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[37] = {
 		["key_name"]=37,
		["name"]=[[聚魔法冠]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[38] = {
 		["key_name"]=38,
		["name"]=[[聚魔法链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[39] = {
 		["key_name"]=39,
		["name"]=[[聚魔法镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[40] = {
 		["key_name"]=40,
		["name"]=[[聚魔法戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[41] = {
 		["key_name"]=41,
		["name"]=[[聚魔法带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[42] = {
 		["key_name"]=42,
		["name"]=[[聚魔法靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[43] = {
 		["key_name"]=43,
		["name"]=[[祖玛龙纹]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[44] = {
 		["key_name"]=44,
		["name"]=[[暗咒道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[45] = {
 		["key_name"]=45,
		["name"]=[[暗咒道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=400, 
	},
	[46] = {
 		["key_name"]=46,
		["name"]=[[暗咒道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[47] = {
 		["key_name"]=47,
		["name"]=[[暗咒道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[48] = {
 		["key_name"]=48,
		["name"]=[[暗咒道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[49] = {
 		["key_name"]=49,
		["name"]=[[暗咒道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[50] = {
 		["key_name"]=50,
		["name"]=[[暗咒道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[51] = {
 		["key_name"]=51,
		["name"]=[[暗咒道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=200, 
	},
	[52] = {
 		["key_name"]=52,
		["name"]=[[神圣屠龙]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[53] = {
 		["key_name"]=53,
		["name"]=[[霸王战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[54] = {
 		["key_name"]=54,
		["name"]=[[霸王战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[55] = {
 		["key_name"]=55,
		["name"]=[[霸王战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[56] = {
 		["key_name"]=56,
		["name"]=[[霸王战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[57] = {
 		["key_name"]=57,
		["name"]=[[霸王战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[58] = {
 		["key_name"]=58,
		["name"]=[[霸王战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[59] = {
 		["key_name"]=59,
		["name"]=[[霸王战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[60] = {
 		["key_name"]=60,
		["name"]=[[霸王战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[61] = {
 		["key_name"]=61,
		["name"]=[[神圣嗜魂]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[62] = {
 		["key_name"]=62,
		["name"]=[[离魂魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[63] = {
 		["key_name"]=63,
		["name"]=[[离魂魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[64] = {
 		["key_name"]=64,
		["name"]=[[聚魂魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[65] = {
 		["key_name"]=65,
		["name"]=[[聚魂魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[66] = {
 		["key_name"]=66,
		["name"]=[[聚魂魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[67] = {
 		["key_name"]=67,
		["name"]=[[聚魂魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[68] = {
 		["key_name"]=68,
		["name"]=[[聚魂魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[69] = {
 		["key_name"]=69,
		["name"]=[[聚魂魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[70] = {
 		["key_name"]=70,
		["name"]=[[神圣逍遥扇]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[71] = {
 		["key_name"]=71,
		["name"]=[[天机道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[72] = {
 		["key_name"]=72,
		["name"]=[[天机道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=600, 
	},
	[73] = {
 		["key_name"]=73,
		["name"]=[[天机道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[74] = {
 		["key_name"]=74,
		["name"]=[[天机道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[75] = {
 		["key_name"]=75,
		["name"]=[[天机道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[76] = {
 		["key_name"]=76,
		["name"]=[[天机道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[77] = {
 		["key_name"]=77,
		["name"]=[[天机道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[78] = {
 		["key_name"]=78,
		["name"]=[[天机道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=300, 
	},
	[79] = {
 		["key_name"]=79,
		["name"]=[[流光斧]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[80] = {
 		["key_name"]=80,
		["name"]=[[刑天战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[81] = {
 		["key_name"]=81,
		["name"]=[[刑天战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[82] = {
 		["key_name"]=82,
		["name"]=[[刑天战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[83] = {
 		["key_name"]=83,
		["name"]=[[刑天战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[84] = {
 		["key_name"]=84,
		["name"]=[[刑天战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[85] = {
 		["key_name"]=85,
		["name"]=[[刑天战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[86] = {
 		["key_name"]=86,
		["name"]=[[刑天战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[87] = {
 		["key_name"]=87,
		["name"]=[[刑天战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[88] = {
 		["key_name"]=88,
		["name"]=[[聚魔法杖]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[89] = {
 		["key_name"]=89,
		["name"]=[[祝融魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[90] = {
 		["key_name"]=90,
		["name"]=[[祝融魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[91] = {
 		["key_name"]=91,
		["name"]=[[祝融法盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[92] = {
 		["key_name"]=92,
		["name"]=[[祝融法链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[93] = {
 		["key_name"]=93,
		["name"]=[[祝融法镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[94] = {
 		["key_name"]=94,
		["name"]=[[祝融法戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[95] = {
 		["key_name"]=95,
		["name"]=[[祝融法带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[96] = {
 		["key_name"]=96,
		["name"]=[[祝融法靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[97] = {
 		["key_name"]=97,
		["name"]=[[天机棍]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[98] = {
 		["key_name"]=98,
		["name"]=[[阴阳道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[99] = {
 		["key_name"]=99,
		["name"]=[[阴阳道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[100] = {
 		["key_name"]=100,
		["name"]=[[阴阳道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[101] = {
 		["key_name"]=101,
		["name"]=[[阴阳道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[102] = {
 		["key_name"]=102,
		["name"]=[[阴阳道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[103] = {
 		["key_name"]=103,
		["name"]=[[阴阳道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[104] = {
 		["key_name"]=104,
		["name"]=[[阴阳道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[105] = {
 		["key_name"]=105,
		["name"]=[[阴阳道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=500, 
	},
	[106] = {
 		["key_name"]=106,
		["name"]=[[月光斩]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[107] = {
 		["key_name"]=107,
		["name"]=[[天赐战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[108] = {
 		["key_name"]=108,
		["name"]=[[天赐战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[109] = {
 		["key_name"]=109,
		["name"]=[[天赐战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[110] = {
 		["key_name"]=110,
		["name"]=[[天赐战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[111] = {
 		["key_name"]=111,
		["name"]=[[天赐战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[112] = {
 		["key_name"]=112,
		["name"]=[[天赐战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[113] = {
 		["key_name"]=113,
		["name"]=[[天赐战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[114] = {
 		["key_name"]=114,
		["name"]=[[天赐战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[115] = {
 		["key_name"]=115,
		["name"]=[[离魂魔杖]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[116] = {
 		["key_name"]=116,
		["name"]=[[麒麟魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[117] = {
 		["key_name"]=117,
		["name"]=[[麒麟魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[118] = {
 		["key_name"]=118,
		["name"]=[[麒麟魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[119] = {
 		["key_name"]=119,
		["name"]=[[麒麟魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[120] = {
 		["key_name"]=120,
		["name"]=[[麒麟魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[121] = {
 		["key_name"]=121,
		["name"]=[[麒麟魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[122] = {
 		["key_name"]=122,
		["name"]=[[麒麟魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[123] = {
 		["key_name"]=123,
		["name"]=[[麒麟魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[124] = {
 		["key_name"]=124,
		["name"]=[[封魔剑]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[125] = {
 		["key_name"]=125,
		["name"]=[[无极道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[126] = {
 		["key_name"]=126,
		["name"]=[[无极道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1600, 
	},
	[127] = {
 		["key_name"]=127,
		["name"]=[[无极道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[128] = {
 		["key_name"]=128,
		["name"]=[[无极道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[129] = {
 		["key_name"]=129,
		["name"]=[[无极道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[130] = {
 		["key_name"]=130,
		["name"]=[[无极道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[131] = {
 		["key_name"]=131,
		["name"]=[[无极道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[132] = {
 		["key_name"]=132,
		["name"]=[[无极道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=800, 
	},
	[133] = {
 		["key_name"]=133,
		["name"]=[[阎魔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[134] = {
 		["key_name"]=134,
		["name"]=[[龙吟战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[135] = {
 		["key_name"]=135,
		["name"]=[[龙吟战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[136] = {
 		["key_name"]=136,
		["name"]=[[龙吟战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[137] = {
 		["key_name"]=137,
		["name"]=[[龙吟战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[138] = {
 		["key_name"]=138,
		["name"]=[[龙吟战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[139] = {
 		["key_name"]=139,
		["name"]=[[龙吟战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[140] = {
 		["key_name"]=140,
		["name"]=[[龙吟战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[141] = {
 		["key_name"]=141,
		["name"]=[[龙吟战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[142] = {
 		["key_name"]=142,
		["name"]=[[天神法杖]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[143] = {
 		["key_name"]=143,
		["name"]=[[修罗魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[144] = {
 		["key_name"]=144,
		["name"]=[[修罗魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[145] = {
 		["key_name"]=145,
		["name"]=[[修罗魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[146] = {
 		["key_name"]=146,
		["name"]=[[修罗魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[147] = {
 		["key_name"]=147,
		["name"]=[[修罗魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[148] = {
 		["key_name"]=148,
		["name"]=[[修罗魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[149] = {
 		["key_name"]=149,
		["name"]=[[修罗魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[150] = {
 		["key_name"]=150,
		["name"]=[[修罗魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[151] = {
 		["key_name"]=151,
		["name"]=[[银蛇剑]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[152] = {
 		["key_name"]=152,
		["name"]=[[仙风道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[153] = {
 		["key_name"]=153,
		["name"]=[[仙风道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[154] = {
 		["key_name"]=154,
		["name"]=[[仙风道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[155] = {
 		["key_name"]=155,
		["name"]=[[仙风道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[156] = {
 		["key_name"]=156,
		["name"]=[[仙风道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[157] = {
 		["key_name"]=157,
		["name"]=[[仙风道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[158] = {
 		["key_name"]=158,
		["name"]=[[仙风道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[159] = {
 		["key_name"]=159,
		["name"]=[[仙风道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1000, 
	},
	[160] = {
 		["key_name"]=160,
		["name"]=[[鬼王]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[161] = {
 		["key_name"]=161,
		["name"]=[[啸天战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[162] = {
 		["key_name"]=162,
		["name"]=[[啸天战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[163] = {
 		["key_name"]=163,
		["name"]=[[啸天战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[164] = {
 		["key_name"]=164,
		["name"]=[[啸天战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[165] = {
 		["key_name"]=165,
		["name"]=[[啸天战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[166] = {
 		["key_name"]=166,
		["name"]=[[啸天战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[167] = {
 		["key_name"]=167,
		["name"]=[[啸天战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[168] = {
 		["key_name"]=168,
		["name"]=[[啸天战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[169] = {
 		["key_name"]=169,
		["name"]=[[七彩魔刃]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[170] = {
 		["key_name"]=170,
		["name"]=[[暗月魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[171] = {
 		["key_name"]=171,
		["name"]=[[暗月魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[172] = {
 		["key_name"]=172,
		["name"]=[[暗月魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[173] = {
 		["key_name"]=173,
		["name"]=[[暗月魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[174] = {
 		["key_name"]=174,
		["name"]=[[暗月魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[175] = {
 		["key_name"]=175,
		["name"]=[[暗月魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[176] = {
 		["key_name"]=176,
		["name"]=[[暗月魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[177] = {
 		["key_name"]=177,
		["name"]=[[暗月魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[178] = {
 		["key_name"]=178,
		["name"]=[[破魂剑]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[179] = {
 		["key_name"]=179,
		["name"]=[[太玄道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[180] = {
 		["key_name"]=180,
		["name"]=[[太玄道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[181] = {
 		["key_name"]=181,
		["name"]=[[太玄道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[182] = {
 		["key_name"]=182,
		["name"]=[[太玄道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[183] = {
 		["key_name"]=183,
		["name"]=[[太玄道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[184] = {
 		["key_name"]=184,
		["name"]=[[太玄道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[185] = {
 		["key_name"]=185,
		["name"]=[[太玄道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[186] = {
 		["key_name"]=186,
		["name"]=[[太玄道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=1500, 
	},
	[187] = {
 		["key_name"]=187,
		["name"]=[[狂雷]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[188] = {
 		["key_name"]=188,
		["name"]=[[追日战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[189] = {
 		["key_name"]=189,
		["name"]=[[追日战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[190] = {
 		["key_name"]=190,
		["name"]=[[追日战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[191] = {
 		["key_name"]=191,
		["name"]=[[追日战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[192] = {
 		["key_name"]=192,
		["name"]=[[追日战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[193] = {
 		["key_name"]=193,
		["name"]=[[追日战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[194] = {
 		["key_name"]=194,
		["name"]=[[追日战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[195] = {
 		["key_name"]=195,
		["name"]=[[追日战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[196] = {
 		["key_name"]=196,
		["name"]=[[千年玄冰]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[197] = {
 		["key_name"]=197,
		["name"]=[[揽月法衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[198] = {
 		["key_name"]=198,
		["name"]=[[揽月法衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[199] = {
 		["key_name"]=199,
		["name"]=[[揽月魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[200] = {
 		["key_name"]=200,
		["name"]=[[揽月魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[201] = {
 		["key_name"]=201,
		["name"]=[[揽月魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[202] = {
 		["key_name"]=202,
		["name"]=[[揽月魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[203] = {
 		["key_name"]=203,
		["name"]=[[揽月魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[204] = {
 		["key_name"]=204,
		["name"]=[[揽月魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[205] = {
 		["key_name"]=205,
		["name"]=[[太乙羽]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[206] = {
 		["key_name"]=206,
		["name"]=[[摘星道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[207] = {
 		["key_name"]=207,
		["name"]=[[摘星道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=4000, 
	},
	[208] = {
 		["key_name"]=208,
		["name"]=[[摘星道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[209] = {
 		["key_name"]=209,
		["name"]=[[摘星道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[210] = {
 		["key_name"]=210,
		["name"]=[[摘星道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[211] = {
 		["key_name"]=211,
		["name"]=[[摘星道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[212] = {
 		["key_name"]=212,
		["name"]=[[摘星道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[213] = {
 		["key_name"]=213,
		["name"]=[[摘星道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=2000, 
	},
	[214] = {
 		["key_name"]=214,
		["name"]=[[破魔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[215] = {
 		["key_name"]=215,
		["name"]=[[金刚战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[216] = {
 		["key_name"]=216,
		["name"]=[[金刚战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[217] = {
 		["key_name"]=217,
		["name"]=[[金刚战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[218] = {
 		["key_name"]=218,
		["name"]=[[金刚战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[219] = {
 		["key_name"]=219,
		["name"]=[[金刚战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[220] = {
 		["key_name"]=220,
		["name"]=[[金刚战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[221] = {
 		["key_name"]=221,
		["name"]=[[金刚战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[222] = {
 		["key_name"]=222,
		["name"]=[[金刚战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[223] = {
 		["key_name"]=223,
		["name"]=[[霜之魂]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[224] = {
 		["key_name"]=224,
		["name"]=[[五行法衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[225] = {
 		["key_name"]=225,
		["name"]=[[五行法衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[226] = {
 		["key_name"]=226,
		["name"]=[[五行魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[227] = {
 		["key_name"]=227,
		["name"]=[[五行魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[228] = {
 		["key_name"]=228,
		["name"]=[[五行魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[229] = {
 		["key_name"]=229,
		["name"]=[[五行魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[230] = {
 		["key_name"]=230,
		["name"]=[[五行魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[231] = {
 		["key_name"]=231,
		["name"]=[[五行魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[232] = {
 		["key_name"]=232,
		["name"]=[[龙鳞羽]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[233] = {
 		["key_name"]=233,
		["name"]=[[神谕道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[234] = {
 		["key_name"]=234,
		["name"]=[[神谕道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=6000, 
	},
	[235] = {
 		["key_name"]=235,
		["name"]=[[神谕道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[236] = {
 		["key_name"]=236,
		["name"]=[[神谕道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[237] = {
 		["key_name"]=237,
		["name"]=[[神谕道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[238] = {
 		["key_name"]=238,
		["name"]=[[神谕道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[239] = {
 		["key_name"]=239,
		["name"]=[[神谕道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[240] = {
 		["key_name"]=240,
		["name"]=[[神谕道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=3000, 
	},
	[241] = {
 		["key_name"]=241,
		["name"]=[[耀光]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[242] = {
 		["key_name"]=242,
		["name"]=[[破坏战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[243] = {
 		["key_name"]=243,
		["name"]=[[破坏战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[244] = {
 		["key_name"]=244,
		["name"]=[[破坏战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[245] = {
 		["key_name"]=245,
		["name"]=[[破坏战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[246] = {
 		["key_name"]=246,
		["name"]=[[破坏战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[247] = {
 		["key_name"]=247,
		["name"]=[[破坏战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[248] = {
 		["key_name"]=248,
		["name"]=[[破坏战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[249] = {
 		["key_name"]=249,
		["name"]=[[破坏战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[250] = {
 		["key_name"]=250,
		["name"]=[[龙之焰]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[251] = {
 		["key_name"]=251,
		["name"]=[[流星魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[252] = {
 		["key_name"]=252,
		["name"]=[[流星魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[253] = {
 		["key_name"]=253,
		["name"]=[[流星魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[254] = {
 		["key_name"]=254,
		["name"]=[[流星魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[255] = {
 		["key_name"]=255,
		["name"]=[[流星魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[256] = {
 		["key_name"]=256,
		["name"]=[[流星魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[257] = {
 		["key_name"]=257,
		["name"]=[[流星魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[258] = {
 		["key_name"]=258,
		["name"]=[[流星魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[259] = {
 		["key_name"]=259,
		["name"]=[[降魔剑]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[260] = {
 		["key_name"]=260,
		["name"]=[[乾坤道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[261] = {
 		["key_name"]=261,
		["name"]=[[乾坤道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=10000, 
	},
	[262] = {
 		["key_name"]=262,
		["name"]=[[乾坤道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[263] = {
 		["key_name"]=263,
		["name"]=[[乾坤道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[264] = {
 		["key_name"]=264,
		["name"]=[[乾坤道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[265] = {
 		["key_name"]=265,
		["name"]=[[乾坤道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[266] = {
 		["key_name"]=266,
		["name"]=[[乾坤道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[267] = {
 		["key_name"]=267,
		["name"]=[[乾坤道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=5000, 
	},
	[268] = {
 		["key_name"]=268,
		["name"]=[[神罚]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[269] = {
 		["key_name"]=269,
		["name"]=[[帝王战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[270] = {
 		["key_name"]=270,
		["name"]=[[帝王战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[271] = {
 		["key_name"]=271,
		["name"]=[[帝王战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[272] = {
 		["key_name"]=272,
		["name"]=[[帝王战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[273] = {
 		["key_name"]=273,
		["name"]=[[帝王战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[274] = {
 		["key_name"]=274,
		["name"]=[[帝王战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[275] = {
 		["key_name"]=275,
		["name"]=[[帝王战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[276] = {
 		["key_name"]=276,
		["name"]=[[帝王战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[277] = {
 		["key_name"]=277,
		["name"]=[[金刚杖]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[278] = {
 		["key_name"]=278,
		["name"]=[[七彩魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[279] = {
 		["key_name"]=279,
		["name"]=[[七彩魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[280] = {
 		["key_name"]=280,
		["name"]=[[七彩魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[281] = {
 		["key_name"]=281,
		["name"]=[[七彩魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[282] = {
 		["key_name"]=282,
		["name"]=[[七彩魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[283] = {
 		["key_name"]=283,
		["name"]=[[七彩魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[284] = {
 		["key_name"]=284,
		["name"]=[[七彩魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[285] = {
 		["key_name"]=285,
		["name"]=[[七彩魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[286] = {
 		["key_name"]=286,
		["name"]=[[金光剑]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[287] = {
 		["key_name"]=287,
		["name"]=[[虚空道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[288] = {
 		["key_name"]=288,
		["name"]=[[虚空道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[289] = {
 		["key_name"]=289,
		["name"]=[[虚空道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[290] = {
 		["key_name"]=290,
		["name"]=[[虚空道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[291] = {
 		["key_name"]=291,
		["name"]=[[虚空道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[292] = {
 		["key_name"]=292,
		["name"]=[[虚空道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[293] = {
 		["key_name"]=293,
		["name"]=[[虚空道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[294] = {
 		["key_name"]=294,
		["name"]=[[虚空道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=8000, 
	},
	[295] = {
 		["key_name"]=295,
		["name"]=[[天火]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[296] = {
 		["key_name"]=296,
		["name"]=[[武圣战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[297] = {
 		["key_name"]=297,
		["name"]=[[武圣战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[298] = {
 		["key_name"]=298,
		["name"]=[[武圣战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[299] = {
 		["key_name"]=299,
		["name"]=[[武圣战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[300] = {
 		["key_name"]=300,
		["name"]=[[武圣战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[301] = {
 		["key_name"]=301,
		["name"]=[[武圣战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[302] = {
 		["key_name"]=302,
		["name"]=[[武圣战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[303] = {
 		["key_name"]=303,
		["name"]=[[武圣战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[304] = {
 		["key_name"]=304,
		["name"]=[[火麒麟]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[305] = {
 		["key_name"]=305,
		["name"]=[[雷神法衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[306] = {
 		["key_name"]=306,
		["name"]=[[雷神法衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[307] = {
 		["key_name"]=307,
		["name"]=[[雷神魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[308] = {
 		["key_name"]=308,
		["name"]=[[雷神魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[309] = {
 		["key_name"]=309,
		["name"]=[[雷神魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[310] = {
 		["key_name"]=310,
		["name"]=[[雷神魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[311] = {
 		["key_name"]=311,
		["name"]=[[雷神魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[312] = {
 		["key_name"]=312,
		["name"]=[[雷神魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[313] = {
 		["key_name"]=313,
		["name"]=[[斩妖剑]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[314] = {
 		["key_name"]=314,
		["name"]=[[泰坦道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[315] = {
 		["key_name"]=315,
		["name"]=[[泰坦道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=24000, 
	},
	[316] = {
 		["key_name"]=316,
		["name"]=[[泰坦道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[317] = {
 		["key_name"]=317,
		["name"]=[[泰坦道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[318] = {
 		["key_name"]=318,
		["name"]=[[泰坦道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[319] = {
 		["key_name"]=319,
		["name"]=[[泰坦道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[320] = {
 		["key_name"]=320,
		["name"]=[[泰坦道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[321] = {
 		["key_name"]=321,
		["name"]=[[泰坦道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=12000, 
	},
	[322] = {
 		["key_name"]=322,
		["name"]=[[赤霄]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[323] = {
 		["key_name"]=323,
		["name"]=[[英雄战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[324] = {
 		["key_name"]=324,
		["name"]=[[英雄战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[325] = {
 		["key_name"]=325,
		["name"]=[[英雄战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[326] = {
 		["key_name"]=326,
		["name"]=[[英雄战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[327] = {
 		["key_name"]=327,
		["name"]=[[英雄战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[328] = {
 		["key_name"]=328,
		["name"]=[[英雄战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[329] = {
 		["key_name"]=329,
		["name"]=[[英雄战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[330] = {
 		["key_name"]=330,
		["name"]=[[英雄战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[331] = {
 		["key_name"]=331,
		["name"]=[[冰与火]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[332] = {
 		["key_name"]=332,
		["name"]=[[魔灵法衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[333] = {
 		["key_name"]=333,
		["name"]=[[魔灵法衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[334] = {
 		["key_name"]=334,
		["name"]=[[魔灵法盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[335] = {
 		["key_name"]=335,
		["name"]=[[魔灵法链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[336] = {
 		["key_name"]=336,
		["name"]=[[魔灵法镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[337] = {
 		["key_name"]=337,
		["name"]=[[魔灵法戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[338] = {
 		["key_name"]=338,
		["name"]=[[魔灵法带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[339] = {
 		["key_name"]=339,
		["name"]=[[魔灵法靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[340] = {
 		["key_name"]=340,
		["name"]=[[真武剑]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[341] = {
 		["key_name"]=341,
		["name"]=[[阐释道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[342] = {
 		["key_name"]=342,
		["name"]=[[阐释道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=32000, 
	},
	[343] = {
 		["key_name"]=343,
		["name"]=[[阐释道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[344] = {
 		["key_name"]=344,
		["name"]=[[阐释道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[345] = {
 		["key_name"]=345,
		["name"]=[[阐释道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[346] = {
 		["key_name"]=346,
		["name"]=[[阐释道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[347] = {
 		["key_name"]=347,
		["name"]=[[阐释道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[348] = {
 		["key_name"]=348,
		["name"]=[[阐释道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=16000, 
	},
	[349] = {
 		["key_name"]=349,
		["name"]=[[绝命]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[350] = {
 		["key_name"]=350,
		["name"]=[[赤龙战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[351] = {
 		["key_name"]=351,
		["name"]=[[赤龙战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[352] = {
 		["key_name"]=352,
		["name"]=[[赤龙战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[353] = {
 		["key_name"]=353,
		["name"]=[[赤龙战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[354] = {
 		["key_name"]=354,
		["name"]=[[赤龙战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[355] = {
 		["key_name"]=355,
		["name"]=[[赤龙战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[356] = {
 		["key_name"]=356,
		["name"]=[[赤龙战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[357] = {
 		["key_name"]=357,
		["name"]=[[赤龙战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[358] = {
 		["key_name"]=358,
		["name"]=[[寒光]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[359] = {
 		["key_name"]=359,
		["name"]=[[追魂魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[360] = {
 		["key_name"]=360,
		["name"]=[[追魂魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[361] = {
 		["key_name"]=361,
		["name"]=[[追魂魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[362] = {
 		["key_name"]=362,
		["name"]=[[追魂魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[363] = {
 		["key_name"]=363,
		["name"]=[[追魂魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[364] = {
 		["key_name"]=364,
		["name"]=[[追魂魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[365] = {
 		["key_name"]=365,
		["name"]=[[追魂魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[366] = {
 		["key_name"]=366,
		["name"]=[[追魂魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[367] = {
 		["key_name"]=367,
		["name"]=[[乾坤法则]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[368] = {
 		["key_name"]=368,
		["name"]=[[昆仑道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[369] = {
 		["key_name"]=369,
		["name"]=[[昆仑道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=40000, 
	},
	[370] = {
 		["key_name"]=370,
		["name"]=[[昆仑道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[371] = {
 		["key_name"]=371,
		["name"]=[[昆仑道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[372] = {
 		["key_name"]=372,
		["name"]=[[昆仑道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[373] = {
 		["key_name"]=373,
		["name"]=[[昆仑道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[374] = {
 		["key_name"]=374,
		["name"]=[[昆仑道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[375] = {
 		["key_name"]=375,
		["name"]=[[昆仑道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=20000, 
	},
	[376] = {
 		["key_name"]=376,
		["name"]=[[龙影]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[377] = {
 		["key_name"]=377,
		["name"]=[[阎罗战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[378] = {
 		["key_name"]=378,
		["name"]=[[阎罗战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[379] = {
 		["key_name"]=379,
		["name"]=[[阎罗战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[380] = {
 		["key_name"]=380,
		["name"]=[[阎罗战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[381] = {
 		["key_name"]=381,
		["name"]=[[阎罗战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[382] = {
 		["key_name"]=382,
		["name"]=[[阎罗战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[383] = {
 		["key_name"]=383,
		["name"]=[[阎罗战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[384] = {
 		["key_name"]=384,
		["name"]=[[阎罗战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[385] = {
 		["key_name"]=385,
		["name"]=[[七星]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[386] = {
 		["key_name"]=386,
		["name"]=[[毁灭魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[387] = {
 		["key_name"]=387,
		["name"]=[[毁灭魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[388] = {
 		["key_name"]=388,
		["name"]=[[毁灭魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[389] = {
 		["key_name"]=389,
		["name"]=[[毁灭魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[390] = {
 		["key_name"]=390,
		["name"]=[[毁灭魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[391] = {
 		["key_name"]=391,
		["name"]=[[毁灭魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[392] = {
 		["key_name"]=392,
		["name"]=[[毁灭魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[393] = {
 		["key_name"]=393,
		["name"]=[[毁灭魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[394] = {
 		["key_name"]=394,
		["name"]=[[灵魂宝镜]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[395] = {
 		["key_name"]=395,
		["name"]=[[避邪道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[396] = {
 		["key_name"]=396,
		["name"]=[[避邪道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=60000, 
	},
	[397] = {
 		["key_name"]=397,
		["name"]=[[避邪道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[398] = {
 		["key_name"]=398,
		["name"]=[[避邪道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[399] = {
 		["key_name"]=399,
		["name"]=[[避邪道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[400] = {
 		["key_name"]=400,
		["name"]=[[避邪道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[401] = {
 		["key_name"]=401,
		["name"]=[[避邪道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[402] = {
 		["key_name"]=402,
		["name"]=[[避邪道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=30000, 
	},
	[403] = {
 		["key_name"]=403,
		["name"]=[[神陨]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[404] = {
 		["key_name"]=404,
		["name"]=[[圣山战甲(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[405] = {
 		["key_name"]=405,
		["name"]=[[圣山战甲(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[406] = {
 		["key_name"]=406,
		["name"]=[[圣山战盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[407] = {
 		["key_name"]=407,
		["name"]=[[圣山战链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[408] = {
 		["key_name"]=408,
		["name"]=[[圣山战镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[409] = {
 		["key_name"]=409,
		["name"]=[[圣山战戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[410] = {
 		["key_name"]=410,
		["name"]=[[圣山战带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[411] = {
 		["key_name"]=411,
		["name"]=[[圣山战靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[412] = {
 		["key_name"]=412,
		["name"]=[[神怒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[413] = {
 		["key_name"]=413,
		["name"]=[[冥王魔衣(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[414] = {
 		["key_name"]=414,
		["name"]=[[冥王魔衣(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[415] = {
 		["key_name"]=415,
		["name"]=[[冥王魔盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[416] = {
 		["key_name"]=416,
		["name"]=[[冥王魔链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[417] = {
 		["key_name"]=417,
		["name"]=[[冥王魔镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[418] = {
 		["key_name"]=418,
		["name"]=[[冥王魔戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[419] = {
 		["key_name"]=419,
		["name"]=[[冥王魔带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[420] = {
 		["key_name"]=420,
		["name"]=[[冥王魔靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[421] = {
 		["key_name"]=421,
		["name"]=[[道法自然]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[422] = {
 		["key_name"]=422,
		["name"]=[[如来道袍(男)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[423] = {
 		["key_name"]=423,
		["name"]=[[如来道袍(女)]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=100000, 
	},
	[424] = {
 		["key_name"]=424,
		["name"]=[[如来道盔]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[425] = {
 		["key_name"]=425,
		["name"]=[[如来道链]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[426] = {
 		["key_name"]=426,
		["name"]=[[如来道镯]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[427] = {
 		["key_name"]=427,
		["name"]=[[如来道戒]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[428] = {
 		["key_name"]=428,
		["name"]=[[如来道带]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},
	[429] = {
 		["key_name"]=429,
		["name"]=[[如来道靴]],
		["givemoney"]=[[绑定元宝]],
		["moneynum"]=50000, 
	},  
}
 return config;