---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["mapname"]=[[5倍高爆地图]],
		["mapid"]=[[1高爆5]],
		["kfmapid"]=[[1kf高爆5]],
		["needitem_arr"]={"5倍高爆地图卷",1,},
		["show_mapid"]=3,
		["npcid"]=1033, 
	},
	[2] = {
 		["key_name"]=2,
		["mapname"]=[[10倍高爆地图]],
		["mapid"]=[[1高爆10]],
		["kfmapid"]=[[1kf高爆10]],
		["needitem_arr"]={"10倍高爆地图卷",1,},
		["show_mapid"]=3,
		["npcid"]=1033, 
	},
	[3] = {
 		["key_name"]=3,
		["mapname"]=[[20倍高爆地图]],
		["mapid"]=[[1高爆20]],
		["kfmapid"]=[[1kf高爆20]],
		["needitem_arr"]={"20倍高爆地图卷",1,},
		["show_mapid"]=3,
		["npcid"]=1033, 
	},
	[4] = {
 		["key_name"]=4,
		["mapname"]=[[30倍高爆地图]],
		["mapid"]=[[1高爆30]],
		["kfmapid"]=[[1kf高爆30]],
		["needitem_arr"]={"30倍高爆地图卷",1,},
		["show_mapid"]=3,
		["npcid"]=1033, 
	},
	[5] = {
 		["key_name"]=5,
		["mapname"]=[[50倍高爆地图]],
		["mapid"]=[[1高爆50]],
		["kfmapid"]=[[1kf高爆50]],
		["needitem_arr"]={"50倍高爆地图卷",1,},
		["show_mapid"]=3,
		["npcid"]=1033, 
	},
	[6] = {
 		["key_name"]=6,
		["mapname"]=[[100倍高爆地图]],
		["mapid"]=[[1高爆100]],
		["kfmapid"]=[[1kf高爆100]],
		["needitem_arr"]={"100倍高爆地图卷",1,},
		["show_mapid"]=3,
		["npcid"]=1033, 
	},
	[7] = {
 		["key_name"]=7,
		["mapname"]=[[5倍高爆地图]],
		["kfmapid"]=[[2kf高爆5]],
		["needitem_arr"]={"5倍高爆地图卷",1,},
		["show_mapid"]=[[bairi]],
		["npcid"]=1034, 
	},
	[8] = {
 		["key_name"]=8,
		["mapname"]=[[10倍高爆地图]],
		["kfmapid"]=[[2kf高爆10]],
		["needitem_arr"]={"10倍高爆地图卷",1,},
		["show_mapid"]=[[bairi]],
		["npcid"]=1034, 
	},
	[9] = {
 		["key_name"]=9,
		["mapname"]=[[20倍高爆地图]],
		["kfmapid"]=[[2kf高爆20]],
		["needitem_arr"]={"20倍高爆地图卷",1,},
		["show_mapid"]=[[bairi]],
		["npcid"]=1034, 
	},
	[10] = {
 		["key_name"]=10,
		["mapname"]=[[30倍高爆地图]],
		["kfmapid"]=[[2kf高爆30]],
		["needitem_arr"]={"30倍高爆地图卷",1,},
		["show_mapid"]=[[bairi]],
		["npcid"]=1034, 
	},
	[11] = {
 		["key_name"]=11,
		["mapname"]=[[50倍高爆地图]],
		["kfmapid"]=[[2kf高爆50]],
		["needitem_arr"]={"50倍高爆地图卷",1,},
		["show_mapid"]=[[bairi]],
		["npcid"]=1034, 
	},
	[12] = {
 		["key_name"]=12,
		["mapname"]=[[100倍高爆地图]],
		["kfmapid"]=[[2kf高爆100]],
		["needitem_arr"]={"100倍高爆地图卷",1,},
		["show_mapid"]=[[bairi]],
		["npcid"]=1034, 
	},
	[13] = {
 		["key_name"]=13,
		["mapname"]=[[5倍高爆地图]],
		["kfmapid"]=[[3kf高爆5]],
		["needitem_arr"]={"5倍高爆地图卷",1,},
		["show_mapid"]=4,
		["npcid"]=1035, 
	},
	[14] = {
 		["key_name"]=14,
		["mapname"]=[[10倍高爆地图]],
		["kfmapid"]=[[3kf高爆10]],
		["needitem_arr"]={"10倍高爆地图卷",1,},
		["show_mapid"]=4,
		["npcid"]=1035, 
	},
	[15] = {
 		["key_name"]=15,
		["mapname"]=[[20倍高爆地图]],
		["kfmapid"]=[[3kf高爆20]],
		["needitem_arr"]={"20倍高爆地图卷",1,},
		["show_mapid"]=4,
		["npcid"]=1035, 
	},
	[16] = {
 		["key_name"]=16,
		["mapname"]=[[30倍高爆地图]],
		["kfmapid"]=[[3kf高爆30]],
		["needitem_arr"]={"30倍高爆地图卷",1,},
		["show_mapid"]=4,
		["npcid"]=1035, 
	},
	[17] = {
 		["key_name"]=17,
		["mapname"]=[[50倍高爆地图]],
		["kfmapid"]=[[3kf高爆50]],
		["needitem_arr"]={"50倍高爆地图卷",1,},
		["show_mapid"]=4,
		["npcid"]=1035, 
	},
	[18] = {
 		["key_name"]=18,
		["mapname"]=[[100倍高爆地图]],
		["kfmapid"]=[[3kf高爆100]],
		["needitem_arr"]={"100倍高爆地图卷",1,},
		["show_mapid"]=4,
		["npcid"]=1035, 
	},  
}
 return config;