---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["job_index"]=[[0_1]],
		["skill_index"]=1,
		["awake_name"]=[[血怒]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60051, 
	},
	[2] = {
 		["key_name"]=2,
		["job_index"]=[[0_1]],
		["skill_index"]=2,
		["awake_name"]=[[屠戮]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60052, 
	},
	[3] = {
 		["key_name"]=3,
		["job_index"]=[[0_1]],
		["skill_index"]=3,
		["awake_name"]=[[狂暴]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60053, 
	},
	[4] = {
 		["key_name"]=4,
		["job_index"]=[[0_1]],
		["skill_index"]=4,
		["awake_name"]=[[斩魄]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60054, 
	},
	[5] = {
 		["key_name"]=5,
		["job_index"]=[[0_1]],
		["skill_index"]=5,
		["awake_name"]=[[无尽怒火]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60055, 
	},
	[6] = {
 		["key_name"]=6,
		["job_index"]=[[0_2]],
		["skill_index"]=1,
		["awake_name"]=[[重刃]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60056, 
	},
	[7] = {
 		["key_name"]=7,
		["job_index"]=[[0_2]],
		["skill_index"]=2,
		["awake_name"]=[[双流]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60057, 
	},
	[8] = {
 		["key_name"]=8,
		["job_index"]=[[0_2]],
		["skill_index"]=3,
		["awake_name"]=[[链舞]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60058, 
	},
	[9] = {
 		["key_name"]=9,
		["job_index"]=[[0_2]],
		["skill_index"]=4,
		["awake_name"]=[[兵魂]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60059, 
	},
	[10] = {
 		["key_name"]=10,
		["job_index"]=[[0_2]],
		["skill_index"]=5,
		["awake_name"]=[[千钧]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60060, 
	},
	[11] = {
 		["key_name"]=11,
		["job_index"]=[[0_3]],
		["skill_index"]=1,
		["awake_name"]=[[剑心]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60061, 
	},
	[12] = {
 		["key_name"]=12,
		["job_index"]=[[0_3]],
		["skill_index"]=2,
		["awake_name"]=[[踏雪]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60062, 
	},
	[13] = {
 		["key_name"]=13,
		["job_index"]=[[0_3]],
		["skill_index"]=3,
		["awake_name"]=[[分影]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60063, 
	},
	[14] = {
 		["key_name"]=14,
		["job_index"]=[[0_3]],
		["skill_index"]=4,
		["awake_name"]=[[剑罡]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60064, 
	},
	[15] = {
 		["key_name"]=15,
		["job_index"]=[[0_3]],
		["skill_index"]=5,
		["awake_name"]=[[天剑]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60065, 
	},
	[16] = {
 		["key_name"]=16,
		["job_index"]=[[1_1]],
		["skill_index"]=1,
		["awake_name"]=[[烈炎]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60066, 
	},
	[17] = {
 		["key_name"]=17,
		["job_index"]=[[1_1]],
		["skill_index"]=2,
		["awake_name"]=[[寒髓]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60067, 
	},
	[18] = {
 		["key_name"]=18,
		["job_index"]=[[1_1]],
		["skill_index"]=3,
		["awake_name"]=[[雷域]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60068, 
	},
	[19] = {
 		["key_name"]=19,
		["job_index"]=[[1_1]],
		["skill_index"]=4,
		["awake_name"]=[[元素调和]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60069, 
	},
	[20] = {
 		["key_name"]=20,
		["job_index"]=[[1_1]],
		["skill_index"]=5,
		["awake_name"]=[[法神附体]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60070, 
	},
	[21] = {
 		["key_name"]=21,
		["job_index"]=[[1_2]],
		["skill_index"]=1,
		["awake_name"]=[[蚀骨]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60071, 
	},
	[22] = {
 		["key_name"]=22,
		["job_index"]=[[1_2]],
		["skill_index"]=2,
		["awake_name"]=[[摄魂]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60072, 
	},
	[23] = {
 		["key_name"]=23,
		["job_index"]=[[1_2]],
		["skill_index"]=3,
		["awake_name"]=[[魔藤]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60073, 
	},
	[24] = {
 		["key_name"]=24,
		["job_index"]=[[1_2]],
		["skill_index"]=4,
		["awake_name"]=[[反噬]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60074, 
	},
	[25] = {
 		["key_name"]=25,
		["job_index"]=[[1_2]],
		["skill_index"]=5,
		["awake_name"]=[[深渊召唤]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60075, 
	},
	[26] = {
 		["key_name"]=26,
		["job_index"]=[[1_3]],
		["skill_index"]=1,
		["awake_name"]=[[圣愈]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60076, 
	},
	[27] = {
 		["key_name"]=27,
		["job_index"]=[[1_3]],
		["skill_index"]=2,
		["awake_name"]=[[神佑]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60077, 
	},
	[28] = {
 		["key_name"]=28,
		["job_index"]=[[1_3]],
		["skill_index"]=3,
		["awake_name"]=[[祷言]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60078, 
	},
	[29] = {
 		["key_name"]=29,
		["job_index"]=[[1_3]],
		["skill_index"]=4,
		["awake_name"]=[[天启]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60079, 
	},
	[30] = {
 		["key_name"]=30,
		["job_index"]=[[1_3]],
		["skill_index"]=5,
		["awake_name"]=[[圣光结界]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60080, 
	},
	[31] = {
 		["key_name"]=31,
		["job_index"]=[[2_1]],
		["skill_index"]=1,
		["awake_name"]=[[驱神]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60081, 
	},
	[32] = {
 		["key_name"]=32,
		["job_index"]=[[2_1]],
		["skill_index"]=2,
		["awake_name"]=[[敕令]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60082, 
	},
	[33] = {
 		["key_name"]=33,
		["job_index"]=[[2_1]],
		["skill_index"]=3,
		["awake_name"]=[[御灵]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60083, 
	},
	[34] = {
 		["key_name"]=34,
		["job_index"]=[[2_1]],
		["skill_index"]=4,
		["awake_name"]=[[八卦阵]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60084, 
	},
	[35] = {
 		["key_name"]=35,
		["job_index"]=[[2_1]],
		["skill_index"]=5,
		["awake_name"]=[[四象归一]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60085, 
	},
	[36] = {
 		["key_name"]=36,
		["job_index"]=[[2_2]],
		["skill_index"]=1,
		["awake_name"]=[[阴阳盾]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60086, 
	},
	[37] = {
 		["key_name"]=37,
		["job_index"]=[[2_2]],
		["skill_index"]=2,
		["awake_name"]=[[禁魔]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60087, 
	},
	[38] = {
 		["key_name"]=38,
		["job_index"]=[[2_2]],
		["skill_index"]=3,
		["awake_name"]=[[逆转]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60088, 
	},
	[39] = {
 		["key_name"]=39,
		["job_index"]=[[2_2]],
		["skill_index"]=4,
		["awake_name"]=[[周天]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60089, 
	},
	[40] = {
 		["key_name"]=40,
		["job_index"]=[[2_2]],
		["skill_index"]=5,
		["awake_name"]=[[乾坤倒转]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60090, 
	},
	[41] = {
 		["key_name"]=41,
		["job_index"]=[[2_3]],
		["skill_index"]=1,
		["awake_name"]=[[毒瘴]],
		["need_item"]=[[书页]],
		["need_item_num"]=0,
		["buff_id"]=60091, 
	},
	[42] = {
 		["key_name"]=42,
		["job_index"]=[[2_3]],
		["skill_index"]=2,
		["awake_name"]=[[蚀体]],
		["need_item"]=[[书页]],
		["need_item_num"]=150,
		["buff_id"]=60092, 
	},
	[43] = {
 		["key_name"]=43,
		["job_index"]=[[2_3]],
		["skill_index"]=3,
		["awake_name"]=[[瘟神]],
		["need_item"]=[[书页]],
		["need_item_num"]=500,
		["buff_id"]=60093, 
	},
	[44] = {
 		["key_name"]=44,
		["job_index"]=[[2_3]],
		["skill_index"]=4,
		["awake_name"]=[[尸爆]],
		["need_item"]=[[书页]],
		["need_item_num"]=1200,
		["buff_id"]=60094, 
	},
	[45] = {
 		["key_name"]=45,
		["job_index"]=[[2_3]],
		["skill_index"]=5,
		["awake_name"]=[[万毒体]],
		["need_item"]=[[书页]],
		["need_item_num"]=2500,
		["buff_id"]=60095, 
	},  
}
 return config;