---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["job_name"]=[[战士]],
		["job_index"]=0,
		["skill_name"]=[[刺杀剑术]],
		["skill_id"]=12,
		["skill_icon"]=[[0_1]],
		["sign_name"]=[[圣痕·拔刀印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率对目标造成真实伤害(本次伤害150%)/FCOLOR=250>]], 
	},
	[2] = {
 		["key_name"]=2,
		["job_name"]=[[战士]],
		["job_index"]=0,
		["skill_name"]=[[烈火剑法]],
		["skill_id"]=26,
		["skill_icon"]=[[0_2]],
		["sign_name"]=[[圣痕·阎魔印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率对目标造成灼烧伤害/FCOLOR=250>\\<(每秒造成最大生命值1%)，持续3秒/FCOLOR=250>]], 
	},
	[3] = {
 		["key_name"]=3,
		["job_name"]=[[战士]],
		["job_index"]=0,
		["skill_name"]=[[开天斩]],
		["skill_id"]=66,
		["skill_icon"]=[[0_3]],
		["sign_name"]=[[圣痕·破天印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率对目标造成眩晕(持续1秒)/FCOLOR=250>]], 
	},
	[4] = {
 		["key_name"]=4,
		["job_name"]=[[战士]],
		["job_index"]=0,
		["skill_name"]=[[逐日剑法]],
		["skill_id"]=56,
		["skill_icon"]=[[0_4]],
		["sign_name"]=[[圣痕·弑魂印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率对目标造成当前HP20%的伤害/FCOLOR=250>\\<同时自身恢复最大生命值10%/FCOLOR=250>]], 
	},
	[5] = {
 		["key_name"]=5,
		["job_name"]=[[法师]],
		["job_index"]=1,
		["skill_name"]=[[火墙]],
		["skill_id"]=22,
		["skill_icon"]=[[1_1]],
		["sign_name"]=[[圣痕·魔宗印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率对目标造成绿毒伤害/FCOLOR=250>\\<同时双防降低50%，持续3秒/FCOLOR=250>]], 
	},
	[6] = {
 		["key_name"]=6,
		["job_name"]=[[法师]],
		["job_index"]=1,
		["skill_name"]=[[魔法盾]],
		["skill_id"]=31,
		["skill_icon"]=[[1_2]],
		["sign_name"]=[[圣痕·金刚印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率免疫本次伤害/FCOLOR=250>\\<且10秒内双防增加50%，持续3秒/FCOLOR=250>]], 
	},
	[7] = {
 		["key_name"]=7,
		["job_name"]=[[法师]],
		["job_index"]=1,
		["skill_name"]=[[灭天火]],
		["skill_id"]=45,
		["skill_icon"]=[[1_3]],
		["sign_name"]=[[圣痕·火龙印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率召唤流星对目标造成最大生命5%伤害/FCOLOR=250>\\<且自身恢复10%的最大生命值/FCOLOR=250>]], 
	},
	[8] = {
 		["key_name"]=8,
		["job_name"]=[[法师]],
		["job_index"]=1,
		["skill_name"]=[[流星火雨]],
		["skill_id"]=58,
		["skill_icon"]=[[1_4]],
		["sign_name"]=[[圣痕·雷霆印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率释放雷霆万钧/FCOLOR=250>\\<对目标区域3*3的范围造成2次伤害。/FCOLOR=250>]], 
	},
	[9] = {
 		["key_name"]=9,
		["job_name"]=[[道士]],
		["job_index"]=2,
		["skill_name"]=[[施毒术]],
		["skill_id"]=6,
		["skill_icon"]=[[2_1]],
		["sign_name"]=[[圣痕·诅咒印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率时中毒的目标进入失明状态/FCOLOR=250>\\<且造成每秒掉血2%，持续3秒。/FCOLOR=250>]], 
	},
	[10] = {
 		["key_name"]=10,
		["job_name"]=[[道士]],
		["job_index"]=2,
		["skill_name"]=[[灵魂火符]],
		["skill_id"]=13,
		["skill_icon"]=[[2_2]],
		["sign_name"]=[[圣痕·裂神印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率对目标区域弹射最多5个火符/FCOLOR=250>\\<且目标本身进入禁锢1秒。/FCOLOR=250>]], 
	},
	[11] = {
 		["key_name"]=11,
		["job_name"]=[[道士]],
		["job_index"]=2,
		["skill_name"]=[[召唤神兽]],
		["skill_id"]=30,
		["skill_icon"]=[[2_3]],
		["sign_name"]=[[圣痕·契约印]],
		["trigger_odds"]=[[100#100#100]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<契约印Lv1.进化召唤兽【强化神兽/强化白虎/强化月灵】/FCOLOR=250>\\<契约印Lv2.进化召唤兽【超级神兽/超级白虎/超级月灵】/FCOLOR=250>\\<契约印Lv3.进化召唤兽【暴走神兽/疯狂白虎/神圣月灵】/FCOLOR=250>]], 
	},
	[12] = {
 		["key_name"]=12,
		["job_name"]=[[道士]],
		["job_index"]=2,
		["skill_name"]=[[飓风破]],
		["skill_id"]=52,
		["skill_icon"]=[[2_4]],
		["sign_name"]=[[圣痕·暴风印]],
		["trigger_odds"]=[[2#5#8]],
		["active_level"]=[[3#6#9]],
		["sign_desc"]=[[<几率召唤全屏多个飓风【3/6/9】/FCOLOR=250>\\<并对目标造成击退效果/FCOLOR=250>]], 
	},  
}
 return config;