---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
	[1] = {
 		["key_name"]=1,
		["mapname"]=[[盟重省]],
		["mapid"]=3,
		["posx"]=322,
		["posy"]=332,
		["scope"]=5,
		["img"]=[[mcd11]],
		["btn"]=[[btn11]],
		["btnx"]=318,
		["btny"]=146,
		["npcid"]=85, 
	},
	[2] = {
 		["key_name"]=2,
		["mapname"]=[[白日门]],
		["mapid"]=[[bairi]],
		["posx"]=311,
		["posy"]=220,
		["scope"]=5,
		["img"]=[[mcd21]],
		["btn"]=[[btn21]],
		["btnx"]=394,
		["btny"]=258,
		["npcid"]=84, 
	},
	[3] = {
 		["key_name"]=3,
		["mapname"]=[[封魔谷]],
		["mapid"]=4,
		["posx"]=298,
		["posy"]=269,
		["scope"]=2,
		["img"]=[[mcd31]],
		["btn"]=[[btn31]],
		["btnx"]=288,
		["btny"]=220,
		["npcid"]=86, 
	},
	[4] = {
 		["key_name"]=4,
		["mapname"]=[[苍月岛]],
		["mapid"]=[[cangyue]],
		["posx"]=155,
		["posy"]=90,
		["scope"]=2,
		["img"]=[[mcd41]],
		["btn"]=[[btn41]],
		["btnx"]=208,
		["btny"]=106,
		["npcid"]=1, 
	},
	[5] = {
 		["key_name"]=5,
		["mapname"]=[[沙之海]],
		["mapid"]=[[shahai]],
		["posx"]=168,
		["posy"]=146,
		["scope"]=2,
		["img"]=[[mcd51]],
		["btn"]=[[btn51]],
		["btnx"]=70,
		["btny"]=134, 
		["grey"]=1.
	},
	[6] = {
 		["key_name"]=6,
		["mapname"]=[[蛮荒城]],
		["mapid"]=[[n6]],
		["posx"]=124,
		["posy"]=157,
		["scope"]=2,
		["img"]=[[mcd61]],
		["btn"]=[[btn61]],
		["btnx"]=92,
		["btny"]=223,
		["npcid"]=1, 
	},
	[7] = {
 		["key_name"]=7,
		["mapname"]=[[雪原]],
		["mapid"]=[[xueyuan]],
		["posx"]=145,
		["posy"]=57,
		["scope"]=3,
		["img"]=[[mcd71]],
		["btn"]=[[btn71]],
		["btnx"]=357,
		["btny"]=79,
		["npcid"]=1, 
	},
	[8] = {
 		["key_name"]=8,
		["mapname"]=[[风暴峡谷]],
		["mapid"]=[[fbxg]],
		["posx"]=223,
		["posy"]=145,
		["scope"]=2,
		["img"]=[[mcd81]],
		["btn"]=[[btn81]],
		["btnx"]=345,
		["btny"]=342,
		["npcid"]=1, 
	},
	[9] = {
 		["key_name"]=9,
		["mapname"]=[[死亡之海]],
		["mapid"]=[[swzh]],
		["posx"]=687,
		["posy"]=155,
		["scope"]=2,
		["img"]=[[mcd91]],
		["btn"]=[[btn91]],
		["btnx"]=182,
		["btny"]=215, 
		["grey"]=1.
	},
	[10] = {
 		["key_name"]=10,
		["mapname"]=[[未知世界]],
		["mapid"]=[[wzsj]],
		["posx"]=177,
		["posy"]=119,
		["scope"]=2,
		["img"]=[[mcd101]],
		["btn"]=[[btn101]],
		["btnx"]=114,
		["btny"]=317, 
		["grey"]=1.
	},
	[11] = {
 		["key_name"]=11,
		["mapname"]=[[比奇省]],
		["mapid"]=0,
		["posx"]=331,
		["posy"]=265,
		["scope"]=5,
		["img"]=[[mcc1]],
		["btn"]=[[mccb1]],
		["btnx"]=229,
		["btny"]=322,
		["npcid"]=0, 
	},
	[12] = {
 		["key_name"]=12,
		["mapname"]=[[沙巴克]],
		["mapid"]=3,
		["posx"]=340,
		["posy"]=328,
		["scope"]=2,
		["img"]=[[mcc2]],
		["btn"]=[[mccb2]],
		["btnx"]=417,
		["btny"]=144,
		["npcid"]=0, 
	},  
}
 return config;