---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wu.
--- DateTime: 2025/6/7 14:09
--- 
local _IS_DEBUG = SL:GetMetaValue("PLATFORM_WINDOWS")

function LoadAll()
    local server_id = tonumber(SL:GetMetaValue("SERVER_ID")) or 0
    _IS_DEBUG = server_id <= 1000
    SL:release_print("load all file, sever id:", server_id, _IS_DEBUG)

    -- require data
    local dataFiles = {
        "GUILayout/clientData/GameData"
    }
    for k, v in pairs(dataFiles) do
        SL:Require(v, true)
    end

    -- require define
    local defineFiles = {
        "GUILayout/define/ClientProtocolDefine",
        "GUILayout/define/ColorCodeDefine",
        "GUILayout/define/GameEventDefine",
    }
    for k, v in pairs(defineFiles) do
        SL:Require(v, true)
    end

    -- require common
    SL:Require("GUILayout/common/ViewMgr", true)
    SL:Require("GUILayout/common/SysConfigView", true)
    SL:Require("GUILayout/common/CommonProtocol", true)
    SL:Require("GUILayout/common/Animation", true)
    SL:Require("GUILayout/common/CommonFunc", true)
    SL:Require("GUILayout/common/GlobalFunc", true)
    SL:Require("GUILayout/common/RedPointMgr", true)
    SL:Require("GUILayout/common/BitMgr", true)

    -- require npc lua
    local npc_lua_files = SL:GetFilesByPath("GUILayout/view")
    local function require_file(path)
        SL:Print("path: ", path)
        path = string.gsub(path, ".lua", "")
        return SL:Require(path, true)
    end
    for k, v in pairs(npc_lua_files) do        
        if nil == string.find(v, ".lua") then
            local tmp_files = SL:GetFilesByPath("GUILayout/view/"..v)
            for _, _v in pairs(tmp_files) do
                local npc_ui = require_file("GUILayout/view/"..v.."/".._v)
                ViewMgr.addNpcScript(npc_ui.Name, npc_ui)
            end
        else
            local npc_ui = require_file("GUILayout/view/"..v)
            ViewMgr.addNpcScript(npc_ui.Name, npc_ui)
        end
    end

    -- require main btn
    local mainBtnClass = {
        "GUILayout/top/SysRightBtn",
        "GUILayout/top/TopBtn",
    }
    for k, v in pairs(mainBtnClass) do
        SL:Require(v, true)
    end

    SL:Require("GUILayout/DiaoXiang", true)

    SL:ScheduleOnce(function ()
        SL:Require("GUILayout/Mainnearbtn", true)
    end, 3)
end

LoadAll()
