---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["activity_name"]=[[天降财宝]],
		["show_award_list_map"]={[1]={"游戏元宝",1,},[2]={"高级材料",1,},[3]={"稀有道具",1,},[4]={"稀有道具",1,},},
		["map_id"]=[[天降财宝]],
		["mini_mapid"]=100196,
		["new_open_desc"]=[[开区15分钟，60分钟各一次]],
		["is_hequ_activity"]=0,
		["desc"]=[[活动地图<font color='#00ff00'> 每分钟 </font>随机 掉落宝藏<br><font color='#df009f'>海量经验、大量元宝、稀有材料！</font><br>活动地图 <font color='#ff0000'> 无法移动</font><br>只能使用 <font color='#00ffe8'> 随机传送</font>]], 
	},
	[2] = {
 		["key_name"]=2,
		["activity_name"]=[[激情派对]],
		["show_award_list_map"]={[1]={"游戏元宝",1,},[2]={"高级材料",1,},[3]={"稀有道具",1,},[4]={"稀有道具",1,},},
		["map_id"]=[[激情派对]],
		["mini_mapid"]=100195,
		["new_open_desc"]=[[开区30分钟，80分钟各一次]],
		["is_hequ_activity"]=0,
		["desc"]=[[活动地图<font color='#00ff00'> 每秒 </font>获得以下收益:<br>每秒获得<font color='#00ff00'> 10元宝 + 5万经验</font><br><font color='#ff0000'>地图内为神秘人模式，pk不红名<br>击杀敌人+10积分，死亡+5积分<br>积分排名前三玩家</font>获得<font color='#ff00ff'>派对大奖 </font><br><font color='#00ffe8'>每两分钟刷新一只上古稻草人</font>]], 
	},
	[3] = {
 		["key_name"]=3,
		["activity_name"]=[[武林至尊]],
		["show_award_list_map"]={[1]={"游戏元宝",1,},[2]={"高级材料",1,},[3]={"稀有道具",1,},[4]={"稀有道具",1,},},
		["map_id"]=[[武林至尊]],
		["mini_mapid"]=100201,
		["new_open_desc"]=[[开区45分钟开启]],
		["is_hequ_activity"]=0,
		["desc"]=[[地图内<font color='#00ff00'> PK不红名，全体攻击模式 </font><br>地图限时<font color='#00ff00'> 15分钟，前10分钟</font>图内<br>复活，<font color='#00ff00'>10分钟后</font>死亡返回土城！<br><font color='#ff0000'>最终胜出 </font>玩家获得<font color='#ff00ff'> 武林盟主 </font>称号<br><font color='#ffff00'>称号属性1.2倍神力，限时48小时 </font>]], 
	},
	[4] = {
 		["key_name"]=4,
		["activity_name"]=[[夺宝奇兵]],
		["show_award_list_map"]={[1]={"游戏元宝",1,},[2]={"高级材料",1,},[3]={"稀有道具",1,},[4]={"稀有道具",1,},},
		["map_id"]=[[夺宝奇兵]],
		["mini_mapid"]=100198,
		["new_open_desc"]=[[开区120分钟开启]],
		["is_hequ_activity"]=0,
		["desc"]=[[活动开启后地图刷新<font color='#ff0000'> 宝藏守护者</font><br>击杀守护者必爆<font color='#ffff00'>终极宝箱</font>，持有<br><font color='#ffff00'>宝箱</font><font color='#ff0000'>120秒</font>后，自动开宝箱，<font color='#ff0000'>随机</font><br>获得<font color='#ff00ff'> 终极首饰*1</font>，宝箱持有者 <font color='#00ffe8'> 回<br>城 小退 死亡</font>，宝箱掉落活动地图]], 
	},
	[5] = {
 		["key_name"]=5,
		["activity_name"]=[[世界Boss]],
		["show_award_list_map"]={[1]={"游戏元宝",1,},[2]={"高级材料",1,},[3]={"稀有道具",1,},[4]={"稀有道具",1,},},
		["map_id"]=[[世界BOSS]],
		["mini_mapid"]=100197,
		["new_open_desc"]=[[开区150分钟开启]],
		["old_open_desc"]=[[每日18:30分开启]],
		["is_hequ_activity"]=1,
		["desc"]=[[活动开启后地图刷新<font color='#ff0000'> 终极大魔王</font><br>击杀<font color='#ff0000'>终极大魔王</font>必爆<font color='#ff00ff'> 超级装备*1</font><br>活动期间内，每次攻击<font color='#ff0000'>大魔王</font>均可获得<font color='#00ff00'> 经验</font>！合区后<font color='#ff0000'> 经验翻倍</font>！]], 
	},
	[6] = {
 		["key_name"]=6,
		["activity_name"]=[[行会战场]],
		["show_award_list_map"]={[1]={"游戏元宝",1,},[2]={"高级材料",1,},[3]={"稀有道具",1,},[4]={"稀有道具",1,},},
		["map_id"]=[[行会战场]],
		["mini_mapid"]=100199,
		["new_open_desc"]=[[开区180分钟开启]],
		["old_open_desc"]=[[每日23:01分开启]],
		["is_hequ_activity"]=1,
		["desc"]=[[活动开启后地图刷新<font color='#ff0000'> 行会大魔王</font><br>击杀<font color='#ff0000'>行会大魔王</font>必爆<font color='#ff00ff'> 超级装备*1</font><br>活动地图为<font color='#ff0000'>行会成员专属地图</font>，地<br>图内每秒获得<font color='#00ff00'>元宝收益</font>，地图内有<br><font color='#ffff00'>其他行会成员</font> Boss进入<font color='#ff00ff'>无敌状态</font>]], 
	},
	[7] = {
 		["key_name"]=7,
		["activity_name"]=[[乱斗之王]],
		["show_award_list_map"]={[1]={"游戏元宝",1,},[2]={"高级材料",1,},[3]={"稀有道具",1,},[4]={"稀有道具",1,},},
		["map_id"]=[[乱斗之王1]],
		["mini_mapid"]=101000,
		["new_open_desc"]=[[开区240分钟开启]],
		["old_open_desc"]=[[每日19:10分开启]],
		["is_hequ_activity"]=1,
		["desc"]=[[活动开始后地图内刷新一只<font color='#ff0000'>暗黑帝王</font>，击杀<font color='#ff0000'>暗黑帝王</font>后可获得丰厚奖励，站在地图<font color='#ff0000'>圈内中心点</font>可获得每秒<font color='#00ff00'>  20万</font>经验值，活动限时<font color='#00ff00'>10分钟</font>]], 
	},
	[8] = {
 		["key_name"]=8,
		["activity_name"]=[[狂暴霸主]],
		["show_award_list_map"]={[1]={"游戏元宝",1,},[2]={"高级材料",1,},[3]={"稀有道具",1,},[4]={"稀有道具",1,},},
		["map_id"]=[[狂暴霸主]],
		["mini_mapid"]=100200,
		["new_open_desc"]=[[开区300分钟开启]],
		["old_open_desc"]=[[狂暴结界满99层开启]],
		["is_hequ_activity"]=0,
		["desc"]=[[每次击杀<font color='#ff0000'>狂暴之力</font>玩家，封印<font color='#ff0000'>狂暴<br>霸主</font>的结界都将<font color='#fff000'> 增加1层</font>，结界达<br>到<font color='#00ff00'>99层</font>，狂暴之地刷新<font color='#ff0000'>狂暴霸主</font><br>击杀<font color='#ff0000'>霸主</font>将掉落<font color='#ff00ff'>上古神装*1</font>]], 
	},
	[9] = {
 		["key_name"]=9,
		["activity_name"]=[[跨服沙城]],
		["show_award_list_map"]={[1]={"初级装扮宝箱",1,},[2]={"高级装扮宝箱",1,},[3]={"史诗装扮宝箱",1,},},
		["map_id"]=[[跨服沙巴克]],
		["mini_mapid"]=099997,
		["is_hequ_activity"]=0,
		["desc"]=[[合区之后<font color='#ff0000'> 每周三、每周六</font>开启<br>参与条件：开通<font color='#00ff00'> 盟重令 </font>玩家<br><font color='#fff000'>跨服沙城 </font>每<font color='#00ff00'>10秒</font>获得<font color='#df009f'> 1荣誉点</font><br><font color='#fff000'>跨服皇宫 </font>每<font color='#00ff00'>10秒</font>获得<font color='#df009f'> 3荣誉点</font><br><font color='#df009f'>荣誉点</font>可在<font color='#00ffe8'>荣耀商店</font>兑换<font color='#00ff00'>装扮道具</font><br>胜利方：荣誉点*500<br>失败方：荣誉点*300]], 
	},  
}
 return config;