---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["type"]=[[每日任务]],
		["task"]=[[今日任意击杀绿名怪物]],
		["count"]=20,
		["rewardhyd"]=1,
		["param"]=250, 
	},
	[2] = {
 		["key_name"]=2,
		["type"]=[[每日任务]],
		["task"]=[[今日任意击杀粉名怪物]],
		["count"]=3,
		["rewardhyd"]=5,
		["param"]=253, 
	},
	[3] = {
 		["key_name"]=3,
		["type"]=[[每日任务]],
		["task"]=[[今日任意击杀红名怪物]],
		["count"]=3,
		["rewardhyd"]=10,
		["param"]=249, 
	},
	[4] = {
 		["key_name"]=4,
		["type"]=[[每日任务]],
		["task"]=[[今日任意击杀金名怪物]],
		["count"]=3,
		["rewardhyd"]=20,
		["param"]=243, 
	},
	[5] = {
 		["key_name"]=5,
		["type"]=[[每日任务]],
		["task"]=[[今日使用【医疗包】]],
		["count"]=3,
		["rewardhyd"]=5,
		["param"]=[[医疗包]], 
	},
	[6] = {
 		["key_name"]=6,
		["type"]=[[每日任务]],
		["task"]=[[今日使用【能量饮料】]],
		["count"]=3,
		["rewardhyd"]=5,
		["param"]=[[能量饮料]], 
	},
	[7] = {
 		["key_name"]=7,
		["type"]=[[每日任务]],
		["task"]=[[今日挑战【恶魔秘境】]],
		["count"]=3,
		["rewardhyd"]=5,
		["param"]=[[恶魔秘境]], 
	},
	[8] = {
 		["key_name"]=8,
		["type"]=[[每日任务]],
		["task"]=[[今日任意充值]],
		["count"]=1,
		["rewardhyd"]=150,
		["param"]=[[今日充值]], 
	},
	[9] = {
 		["key_name"]=9,
		["type"]=[[每日任务]],
		["task"]=[[今日使用1亿经验珠]],
		["count"]=3,
		["rewardhyd"]=10,
		["param"]=[[100万经验珠]], 
	},
	[10] = {
 		["key_name"]=10,
		["type"]=[[每日任务]],
		["task"]=[[今日领取周享礼包]],
		["count"]=1,
		["rewardhyd"]=150,
		["param"]=[[每日周享礼包]], 
	},
	[11] = {
 		["key_name"]=11,
		["type"]=[[达成奖励]],
		["reward_arr"]={"书页",20,},
		["totalhyd"]=30, 
	},
	[12] = {
 		["key_name"]=12,
		["type"]=[[达成奖励]],
		["reward_arr"]={"金针",30,},
		["totalhyd"]=80, 
	},
	[13] = {
 		["key_name"]=13,
		["type"]=[[达成奖励]],
		["reward_arr"]={"黑铁",50,},
		["totalhyd"]=150, 
	},
	[14] = {
 		["key_name"]=14,
		["type"]=[[达成奖励]],
		["reward_arr"]={"龙鳞",50,},
		["totalhyd"]=240, 
	},
	[15] = {
 		["key_name"]=15,
		["type"]=[[达成奖励]],
		["reward_arr"]={"转生凭证",50,},
		["totalhyd"]=360, 
	},
	[16] = {
 		["key_name"]=16,
		["type"]=[[达成奖励]],
		["reward_arr"]={"五行精华",100,},
		["totalhyd"]=420, 
	},
	[17] = {
 		["key_name"]=17,
		["type"]=[[达成奖励]],
		["reward_arr"]={"玛法宝典",1,},
		["totalhyd"]=500, 
	},
	[18] = {
 		["key_name"]=18,
		["type"]=[[兑换奖励]],
		["reward_arr"]={"医疗包",1,},
		["needhyd"]=100, 
	},
	[19] = {
 		["key_name"]=19,
		["type"]=[[兑换奖励]],
		["reward_arr"]={"血纹盾",1,},
		["needhyd"]=100, 
	},
	[20] = {
 		["key_name"]=20,
		["type"]=[[兑换奖励]],
		["reward_arr"]={"罗盘",1,},
		["needhyd"]=200, 
	},
}
 return config;