---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["attr_name"]=[[生命值]],
		["attrid"]=1,
		["attr_max"]=999,
		["attr_value"]=1,
		["need_talent"]=1, 
	},
	[2] = {
 		["key_name"]=2,
		["attr_name"]=[[魔法值]],
		["attrid"]=2,
		["attr_max"]=999,
		["attr_value"]=1,
		["need_talent"]=1, 
	},
	[3] = {
 		["key_name"]=3,
		["attr_name"]=[[防御下限]],
		["attrid"]=9,
		["attr_max"]=99,
		["attr_value"]=1,
		["need_talent"]=2, 
	},
	[4] = {
 		["key_name"]=4,
		["attr_name"]=[[防御上限]],
		["attrid"]=10,
		["attr_max"]=99,
		["attr_value"]=1,
		["need_talent"]=2, 
	},
	[5] = {
 		["key_name"]=5,
		["attr_name"]=[[魔防下限]],
		["attrid"]=11,
		["attr_max"]=99,
		["attr_value"]=1,
		["need_talent"]=2, 
	},
	[6] = {
 		["key_name"]=6,
		["attr_name"]=[[魔防上限]],
		["attrid"]=12,
		["attr_max"]=99,
		["attr_value"]=1,
		["need_talent"]=2, 
	},
	[7] = {
 		["key_name"]=7,
		["attr_name"]=[[攻击下限]],
		["attrid"]=3,
		["attr_max"]=99,
		["attr_value"]=1,
		["need_talent"]=3, 
	},
	[8] = {
 		["key_name"]=8,
		["attr_name"]=[[攻击上限]],
		["attrid"]=4,
		["attr_max"]=99,
		["attr_value"]=1,
		["need_talent"]=3, 
	},
	[9] = {
 		["key_name"]=9,
		["attr_name"]=[[生命加成]],
		["attrid"]=60,
		["attr_max"]=9999,
		["attr_value"]=1,
		["weight"]=1000, 
	},
	[10] = {
 		["key_name"]=10,
		["attr_name"]=[[防御加成]],
		["attrid"]=36,
		["attr_max"]=20,
		["attr_value"]=1,
		["weight"]=300, 
	},
	[11] = {
 		["key_name"]=11,
		["attr_name"]=[[魔防加成]],
		["attrid"]=37,
		["attr_max"]=20,
		["attr_value"]=1,
		["weight"]=300, 
	},
	[12] = {
 		["key_name"]=12,
		["attr_name"]=[[攻击伤害]],
		["attrid"]=67,
		["attr_max"]=10,
		["attr_value"]=1,
		["weight"]=100, 
	},
	[13] = {
 		["key_name"]=13,
		["attr_name"]=[[暴击伤害]],
		["attrid"]=22,
		["attr_max"]=10,
		["attr_value"]=1,
		["weight"]=50, 
	},  
}
 return config;