---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["equip_type_name"]=[[祖玛装备]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"绿色项链","骑士手镯","力量戒指","恶魔铃铛","龙之手镯","紫碧螺","灵魂项链","三眼手镯","泰坦戒指",},
		["hp_attr"]=1,
		["attack_attr1"]=1,
		["active_suit_num"]=9,
		["quick_need"]=1, 
	},
	[2] = {
 		["key_name"]=2,
		["equip_type_name"]=[[圣战系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"圣战头盔","圣战项链","圣战手镯","圣战戒指",},
		["hp_attr"]=2,
		["attack_attr1"]=1,
		["active_suit_num"]=4,
		["quick_need"]=1, 
	},
	[3] = {
 		["key_name"]=3,
		["equip_type_name"]=[[法神系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"法神头盔","法神项链","法神手镯","法神戒指",},
		["hp_attr"]=2,
		["attack_attr2"]=1,
		["active_suit_num"]=4,
		["quick_need"]=1, 
	},
	[4] = {
 		["key_name"]=4,
		["equip_type_name"]=[[天尊系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"天尊头盔","天尊项链","天尊手镯","天尊戒指",},
		["hp_attr"]=2,
		["attack_attr3"]=1,
		["active_suit_num"]=4,
		["quick_need"]=1, 
	},
	[5] = {
 		["key_name"]=5,
		["equip_type_name"]=[[雷霆系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"雷霆项链","雷霆护腕","雷霆战戒","雷霆腰带","雷霆战靴",},
		["hp_attr"]=3,
		["attack_attr1"]=1,
		["active_suit_num"]=5,
		["quick_need"]=1, 
	},
	[6] = {
 		["key_name"]=6,
		["equip_type_name"]=[[烈焰系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"烈焰项链","烈焰护腕","烈焰魔戒","烈焰腰带","烈焰魔靴",},
		["hp_attr"]=3,
		["attack_attr2"]=2,
		["active_suit_num"]=5,
		["quick_need"]=1, 
	},
	[7] = {
 		["key_name"]=7,
		["equip_type_name"]=[[光芒系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"光芒项链","光芒护腕","光芒道戒","光芒腰带","光芒道靴",},
		["hp_attr"]=3,
		["attack_attr3"]=2,
		["active_suit_num"]=5,
		["quick_need"]=1, 
	},
	[8] = {
 		["key_name"]=8,
		["equip_type_name"]=[[战神系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"战神项链","战神手镯","战神戒指","战神腰带","战神靴子",},
		["hp_attr"]=4,
		["attack_attr1"]=1,
		["active_suit_num"]=5,
		["quick_need"]=1, 
	},
	[9] = {
 		["key_name"]=9,
		["equip_type_name"]=[[圣魔系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"圣魔项链","圣魔手镯","圣魔戒指","圣魔腰带","圣魔靴子",},
		["hp_attr"]=4,
		["attack_attr2"]=2,
		["active_suit_num"]=5,
		["quick_need"]=1, 
	},
	[10] = {
 		["key_name"]=10,
		["equip_type_name"]=[[真魂系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"真魂项链","真魂手镯","真魂戒指","真魂腰带","真魂靴子",},
		["hp_attr"]=4,
		["attack_attr3"]=2,
		["active_suit_num"]=5,
		["quick_need"]=1, 
	},
	[11] = {
 		["key_name"]=11,
		["equip_type_name"]=[[奔雷系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"奔雷项链","奔雷护腕","奔雷战戒","奔雷腰带","奔雷战靴",},
		["hp_attr"]=5,
		["attack_attr1"]=1,
		["active_suit_num"]=5,
		["quick_need"]=3, 
	},
	[12] = {
 		["key_name"]=12,
		["equip_type_name"]=[[怒焰系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"怒焰项链","怒焰护腕","怒焰魔戒","怒焰腰带","怒焰魔靴",},
		["hp_attr"]=5,
		["attack_attr2"]=3,
		["active_suit_num"]=5,
		["quick_need"]=3, 
	},
	[13] = {
 		["key_name"]=13,
		["equip_type_name"]=[[极光系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"极光项链","极光护腕","极光道戒","极光腰带","极光道靴",},
		["hp_attr"]=5,
		["attack_attr3"]=3,
		["active_suit_num"]=5,
		["quick_need"]=3, 
	},
	[14] = {
 		["key_name"]=14,
		["equip_type_name"]=[[虎啸系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"虎啸战盔","虎啸战链","虎啸战镯","虎啸战戒","虎啸战带","虎啸战靴",},
		["hp_attr"]=6,
		["attack_attr1"]=1,
		["active_suit_num"]=6,
		["quick_need"]=3, 
	},
	[15] = {
 		["key_name"]=15,
		["equip_type_name"]=[[聚魔系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"聚魔法冠","聚魔法链","聚魔法镯","聚魔法戒","聚魔法带","聚魔法靴",},
		["hp_attr"]=6,
		["attack_attr2"]=3,
		["active_suit_num"]=6,
		["quick_need"]=3, 
	},
	[16] = {
 		["key_name"]=16,
		["equip_type_name"]=[[暗咒系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"暗咒道盔","暗咒道链","暗咒道镯","暗咒道戒","暗咒道带","暗咒道靴",},
		["hp_attr"]=6,
		["attack_attr3"]=3,
		["active_suit_num"]=6,
		["quick_need"]=3, 
	},
	[17] = {
 		["key_name"]=17,
		["equip_type_name"]=[[霸王系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"霸王战盔","霸王战链","霸王战镯","霸王战戒","霸王战带","霸王战靴",},
		["hp_attr"]=7,
		["attack_attr1"]=1,
		["active_suit_num"]=6,
		["quick_need"]=3, 
	},
	[18] = {
 		["key_name"]=18,
		["equip_type_name"]=[[聚魂系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"聚魂魔盔","聚魂魔链","聚魂魔镯","聚魂魔戒","聚魂魔带","聚魂魔靴",},
		["hp_attr"]=7,
		["attack_attr2"]=4,
		["active_suit_num"]=6,
		["quick_need"]=3, 
	},
	[19] = {
 		["key_name"]=19,
		["equip_type_name"]=[[天机系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"天机道盔","天机道链","天机道镯","天机道戒","天机道带","天机道靴",},
		["hp_attr"]=7,
		["attack_attr3"]=4,
		["active_suit_num"]=6,
		["quick_need"]=3, 
	},
	[20] = {
 		["key_name"]=20,
		["equip_type_name"]=[[刑天系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"刑天战盔","刑天战链","刑天战镯","刑天战戒","刑天战带","刑天战靴",},
		["hp_attr"]=8,
		["attack_attr1"]=1,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[21] = {
 		["key_name"]=21,
		["equip_type_name"]=[[祝融系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"祝融法盔","祝融法链","祝融法镯","祝融法戒","祝融法带","祝融法靴",},
		["hp_attr"]=8,
		["attack_attr2"]=4,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[22] = {
 		["key_name"]=22,
		["equip_type_name"]=[[阴阳系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"阴阳道盔","阴阳道链","阴阳道镯","阴阳道戒","阴阳道带","阴阳道靴",},
		["hp_attr"]=8,
		["attack_attr3"]=4,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[23] = {
 		["key_name"]=23,
		["equip_type_name"]=[[天赐系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"天赐战盔","天赐战链","天赐战镯","天赐战戒","天赐战带","天赐战靴",},
		["hp_attr"]=9,
		["attack_attr1"]=1,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[24] = {
 		["key_name"]=24,
		["equip_type_name"]=[[麒麟系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"麒麟魔盔","麒麟魔链","麒麟魔镯","麒麟魔戒","麒麟魔带","麒麟魔靴",},
		["hp_attr"]=9,
		["attack_attr2"]=5,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[25] = {
 		["key_name"]=25,
		["equip_type_name"]=[[无极系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"无极道盔","无极道链","无极道镯","无极道戒","无极道带","无极道靴",},
		["hp_attr"]=9,
		["attack_attr3"]=5,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[26] = {
 		["key_name"]=26,
		["equip_type_name"]=[[龙吟系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"龙吟战盔","龙吟战链","龙吟战镯","龙吟战戒","龙吟战带","龙吟战靴",},
		["hp_attr"]=10,
		["attack_attr1"]=1,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[27] = {
 		["key_name"]=27,
		["equip_type_name"]=[[修罗系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"修罗魔盔","修罗魔链","修罗魔镯","修罗魔戒","修罗魔带","修罗魔靴",},
		["hp_attr"]=10,
		["attack_attr2"]=5,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[28] = {
 		["key_name"]=28,
		["equip_type_name"]=[[仙风系列]],
		["show_mapid"]=0,
		["btn_color"]=255,
		["equip_list"]={"仙风道盔","仙风道链","仙风道镯","仙风道戒","仙风道带","仙风道靴",},
		["hp_attr"]=10,
		["attack_attr3"]=5,
		["active_suit_num"]=6,
		["quick_need"]=5, 
	},
	[29] = {
 		["key_name"]=29,
		["equip_type_name"]=[[啸天系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"啸天战盔","啸天战链","啸天战镯","啸天战戒","啸天战带","啸天战靴",},
		["hp_attr"]=10,
		["attack_attr1"]=2,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[30] = {
 		["key_name"]=30,
		["equip_type_name"]=[[暗月系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"暗月魔盔","暗月魔链","暗月魔镯","暗月魔戒","暗月魔带","暗月魔靴",},
		["hp_attr"]=10,
		["attack_attr2"]=6,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[31] = {
 		["key_name"]=31,
		["equip_type_name"]=[[太玄系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"太玄道盔","太玄道链","太玄道镯","太玄道戒","太玄道带","太玄道靴",},
		["hp_attr"]=10,
		["attack_attr3"]=6,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[32] = {
 		["key_name"]=32,
		["equip_type_name"]=[[追日系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"追日战盔","追日战链","追日战镯","追日战戒","追日战带","追日战靴",},
		["hp_attr"]=12,
		["attack_attr1"]=2,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[33] = {
 		["key_name"]=33,
		["equip_type_name"]=[[揽月系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"揽月魔盔","揽月魔链","揽月魔镯","揽月魔戒","揽月魔带","揽月魔靴",},
		["hp_attr"]=12,
		["attack_attr2"]=6,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[34] = {
 		["key_name"]=34,
		["equip_type_name"]=[[摘星系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"摘星道盔","摘星道链","摘星道镯","摘星道戒","摘星道带","摘星道靴",},
		["hp_attr"]=12,
		["attack_attr3"]=6,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[35] = {
 		["key_name"]=35,
		["equip_type_name"]=[[金刚系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"金刚战盔","金刚战链","金刚战镯","金刚战戒","金刚战带","金刚战靴",},
		["hp_attr"]=12,
		["attack_attr1"]=2,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[36] = {
 		["key_name"]=36,
		["equip_type_name"]=[[五行系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"五行魔盔","五行魔链","五行魔镯","五行魔戒","五行魔带","五行魔靴",},
		["hp_attr"]=12,
		["attack_attr2"]=7,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[37] = {
 		["key_name"]=37,
		["equip_type_name"]=[[神谕系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"神谕道盔","神谕道链","神谕道镯","神谕道戒","神谕道带","神谕道靴",},
		["hp_attr"]=12,
		["attack_attr3"]=7,
		["active_suit_num"]=6,
		["quick_need"]=8, 
	},
	[38] = {
 		["key_name"]=38,
		["equip_type_name"]=[[破坏系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"破坏战盔","破坏战链","破坏战镯","破坏战戒","破坏战带","破坏战靴",},
		["hp_attr"]=14,
		["attack_attr1"]=2,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[39] = {
 		["key_name"]=39,
		["equip_type_name"]=[[流星系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"流星魔盔","流星魔链","流星魔镯","流星魔戒","流星魔带","流星魔靴",},
		["hp_attr"]=14,
		["attack_attr2"]=7,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[40] = {
 		["key_name"]=40,
		["equip_type_name"]=[[乾坤系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"乾坤道盔","乾坤道链","乾坤道镯","乾坤道戒","乾坤道带","乾坤道靴",},
		["hp_attr"]=14,
		["attack_attr3"]=7,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[41] = {
 		["key_name"]=41,
		["equip_type_name"]=[[帝王系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"帝王战盔","帝王战链","帝王战镯","帝王战戒","帝王战带","帝王战靴",},
		["hp_attr"]=14,
		["attack_attr1"]=2,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[42] = {
 		["key_name"]=42,
		["equip_type_name"]=[[七彩系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"七彩魔盔","七彩魔链","七彩魔镯","七彩魔戒","七彩魔带","七彩魔靴",},
		["hp_attr"]=14,
		["attack_attr2"]=8,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[43] = {
 		["key_name"]=43,
		["equip_type_name"]=[[虚空系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"虚空道盔","虚空道链","虚空道镯","虚空道戒","虚空道带","虚空道靴",},
		["hp_attr"]=14,
		["attack_attr3"]=8,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[44] = {
 		["key_name"]=44,
		["equip_type_name"]=[[武圣系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"武圣战盔","武圣战链","武圣战镯","武圣战戒","武圣战带","武圣战靴",},
		["hp_attr"]=16,
		["attack_attr1"]=2,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[45] = {
 		["key_name"]=45,
		["equip_type_name"]=[[雷神系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"雷神魔盔","雷神魔链","雷神魔镯","雷神魔戒","雷神魔带","雷神魔靴",},
		["hp_attr"]=16,
		["attack_attr2"]=8,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[46] = {
 		["key_name"]=46,
		["equip_type_name"]=[[泰坦系列]],
		["show_mapid"]=2,
		["btn_color"]=255,
		["equip_list"]={"泰坦道盔","泰坦道链","泰坦道镯","泰坦道戒","泰坦道带","泰坦道靴",},
		["hp_attr"]=16,
		["attack_attr3"]=8,
		["active_suit_num"]=6,
		["quick_need"]=10, 
	},
	[47] = {
 		["key_name"]=47,
		["equip_type_name"]=[[英雄系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"英雄战盔","英雄战链","英雄战镯","英雄战戒","英雄战带","英雄战靴",},
		["hp_attr"]=16,
		["attack_attr1"]=2,
		["active_suit_num"]=6, 
	},
	[48] = {
 		["key_name"]=48,
		["equip_type_name"]=[[魔灵系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"魔灵法盔","魔灵法链","魔灵法镯","魔灵法戒","魔灵法带","魔灵法靴",},
		["hp_attr"]=16,
		["attack_attr2"]=9,
		["active_suit_num"]=6, 
	},
	[49] = {
 		["key_name"]=49,
		["equip_type_name"]=[[阐释系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"阐释道盔","阐释道链","阐释道镯","阐释道戒","阐释道带","阐释道靴",},
		["hp_attr"]=16,
		["attack_attr3"]=9,
		["active_suit_num"]=6, 
	},
	[50] = {
 		["key_name"]=50,
		["equip_type_name"]=[[赤龙系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"赤龙战盔","赤龙战链","赤龙战镯","赤龙战戒","赤龙战带","赤龙战靴",},
		["hp_attr"]=18,
		["attack_attr1"]=2,
		["active_suit_num"]=6, 
	},
	[51] = {
 		["key_name"]=51,
		["equip_type_name"]=[[追魂系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"追魂魔盔","追魂魔链","追魂魔镯","追魂魔戒","追魂魔带","追魂魔靴",},
		["hp_attr"]=18,
		["attack_attr2"]=9,
		["active_suit_num"]=6, 
	},
	[52] = {
 		["key_name"]=52,
		["equip_type_name"]=[[昆仑系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"昆仑道盔","昆仑道链","昆仑道镯","昆仑道戒","昆仑道带","昆仑道靴",},
		["hp_attr"]=18,
		["attack_attr3"]=9,
		["active_suit_num"]=6, 
	},
	[53] = {
 		["key_name"]=53,
		["equip_type_name"]=[[阎罗系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"阎罗战盔","阎罗战链","阎罗战镯","阎罗战戒","阎罗战带","阎罗战靴",},
		["hp_attr"]=18,
		["attack_attr1"]=2,
		["active_suit_num"]=6, 
	},
	[54] = {
 		["key_name"]=54,
		["equip_type_name"]=[[毁灭系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"毁灭魔盔","毁灭魔链","毁灭魔镯","毁灭魔戒","毁灭魔带","毁灭魔靴",},
		["hp_attr"]=18,
		["attack_attr2"]=10,
		["active_suit_num"]=6, 
	},
	[55] = {
 		["key_name"]=55,
		["equip_type_name"]=[[避邪系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"避邪道盔","避邪道链","避邪道镯","避邪道戒","避邪道带","避邪道靴",},
		["hp_attr"]=18,
		["attack_attr3"]=10,
		["active_suit_num"]=6, 
	},
	[56] = {
 		["key_name"]=56,
		["equip_type_name"]=[[圣山系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"圣山战盔","圣山战链","圣山战镯","圣山战戒","圣山战带","圣山战靴",},
		["hp_attr"]=20,
		["attack_attr1"]=2,
		["active_suit_num"]=6, 
	},
	[57] = {
 		["key_name"]=57,
		["equip_type_name"]=[[冥王系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"冥王魔盔","冥王魔链","冥王魔镯","冥王魔戒","冥王魔带","冥王魔靴",},
		["hp_attr"]=20,
		["attack_attr2"]=10,
		["active_suit_num"]=6, 
	},
	[58] = {
 		["key_name"]=58,
		["equip_type_name"]=[[如来系列]],
		["show_mapid"]=3,
		["btn_color"]=255,
		["equip_list"]={"如来道盔","如来道链","如来道镯","如来道戒","如来道带","如来道靴",},
		["hp_attr"]=20,
		["attack_attr3"]=10,
		["active_suit_num"]=6, 
	},  
}
 return config;