---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["fashion_type"]=1,
		["npc_id"]=214,
		["mapid"]=[[xueyuan]],
		["map_name"]=[[雪原]],
		["name"]="[魔兽]雪狼王",
		["need_item"]=[[雪原凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=20012,
		["effect_type"]=2, 
	},
	[2] = {
 		["key_name"]=2,
		["fashion_type"]=1,
		["npc_id"]=214,
		["mapid"]=[[xueyuan]],
		["map_name"]=[[雪原]],
		["name"]="[魔兽]麒麟兽",
		["need_item"]=[[雪原凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=20013,
		["effect_type"]=2, 
	},
	[3] = {
 		["key_name"]=3,
		["fashion_type"]=1,
		["npc_id"]=214,
		["mapid"]=[[xueyuan]],
		["map_name"]=[[雪原]],
		["name"]="[魔兽]地狱牛",
		["need_item"]=[[雪原凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=20014,
		["effect_type"]=2, 
	},
	[4] = {
 		["key_name"]=4,
		["fashion_type"]=2,
		["npc_id"]=213,
		["mapid"]=[[fbxg]],
		["map_name"]=[[风暴峡谷]],
		["name"]="[时装]无畏冲锋",
		["need_item"]=[[风暴凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=17041,
		["effect_type"]=4, 
	},
	[5] = {
 		["key_name"]=5,
		["fashion_type"]=2,
		["npc_id"]=213,
		["mapid"]=[[fbxg]],
		["map_name"]=[[风暴峡谷]],
		["name"]="[时装]灵魂舞者",
		["need_item"]=[[风暴凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=17043,
		["effect_type"]=4, 
	},
	[6] = {
 		["key_name"]=6,
		["fashion_type"]=2,
		["npc_id"]=213,
		["mapid"]=[[fbxg]],
		["map_name"]=[[风暴峡谷]],
		["name"]="[时装]暴风巨斧",
		["need_item"]=[[风暴凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=17054,
		["effect_type"]=4, 
	},
	[7] = {
 		["key_name"]=7,
		["fashion_type"]=3,
		["npc_id"]=215,
		["mapid"]=[[n6]],
		["map_name"]=[[蛮荒城]],
		["name"]=[[虚空魂环]],
		["need_item"]=[[蛮荒凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=12530,
		["effect_type"]=0, 
	},
	[8] = {
 		["key_name"]=8,
		["fashion_type"]=3,
		["npc_id"]=215,
		["mapid"]=[[n6]],
		["map_name"]=[[蛮荒城]],
		["name"]=[[雷鸣魂环]],
		["need_item"]=[[蛮荒凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=12531,
		["effect_type"]=0, 
	},
	[9] = {
 		["key_name"]=9,
		["fashion_type"]=3,
		["npc_id"]=215,
		["mapid"]=[[n6]],
		["map_name"]=[[蛮荒城]],
		["name"]=[[冰霜魂环]],
		["need_item"]=[[蛮荒凭证]],
		["need_count"]=999,
		["need_item2"]=[[元宝]],
		["need_count2"]=1000000,
		["effect_id"]=12532,
		["effect_type"]=0, 
	},  
}
 return config;