---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["tab_name"]=[[斗笠]],
		["can_inlay_name"]=[[终极斗笠]],
		["equip_pos"]=13,
		["max_level"]=15,
		["inlay_pos1"]=[[红宝石]],
		["inlay_pos2"]=[[黄宝石]],
		["inlay_pos3"]=[[蓝宝石]],
		["inlay_pos4"]=[[绿宝石]],
		["inlay_pos5"]=[[紫水晶]], 
	},
	[2] = {
 		["key_name"]=2,
		["tab_name"]=[[勋章]],
		["can_inlay_name"]=[[终极勋章]],
		["equip_pos"]=2,
		["max_level"]=15,
		["inlay_pos1"]=[[红宝石]],
		["inlay_pos2"]=[[黄宝石]],
		["inlay_pos3"]=[[蓝宝石]],
		["inlay_pos4"]=[[绿宝石]],
		["inlay_pos5"]=[[紫水晶]], 
	},
	[3] = {
 		["key_name"]=3,
		["tab_name"]=[[血石]],
		["can_inlay_name"]=[[终极血石]],
		["equip_pos"]=12,
		["max_level"]=15,
		["inlay_pos1"]=[[红宝石]],
		["inlay_pos2"]=[[黄宝石]],
		["inlay_pos3"]=[[蓝宝石]],
		["inlay_pos4"]=[[绿宝石]],
		["inlay_pos5"]=[[紫水晶]], 
	},
	[4] = {
 		["key_name"]=4,
		["tab_name"]=[[护符]],
		["can_inlay_name"]=[[终极护符]],
		["equip_pos"]=9,
		["max_level"]=15,
		["inlay_pos1"]=[[红宝石]],
		["inlay_pos2"]=[[黄宝石]],
		["inlay_pos3"]=[[蓝宝石]],
		["inlay_pos4"]=[[绿宝石]],
		["inlay_pos5"]=[[紫水晶]], 
	},
	[5] = {
 		["key_name"]=5,
		["tab_name"]=[[军鼓]],
		["can_inlay_name"]=[[终极军鼓]],
		["equip_pos"]=14,
		["max_level"]=15,
		["inlay_pos1"]=[[红宝石]],
		["inlay_pos2"]=[[黄宝石]],
		["inlay_pos3"]=[[蓝宝石]],
		["inlay_pos4"]=[[绿宝石]],
		["inlay_pos5"]=[[紫水晶]], 
	},
	[6] = {
 		["key_name"]=6,
		["tab_name"]=[[盾牌]],
		["can_inlay_name"]=[[创世源初盾]],
		["equip_pos"]=16,
		["max_level"]=9,
		["inlay_pos1"]=[[憎恨结晶]],
		["inlay_pos2"]=[[地狱熔核]],
		["inlay_pos3"]=[[毁灭之心]],
		["inlay_pos4"]=[[闪电水晶]],
		["inlay_pos5"]=[[亡者低语]], 
	},
	[7] = {
 		["key_name"]=7,
		["tab_name"]=[[武器]],
		["can_inlay_name"]=[[武器]],
		["equip_pos"]=1,
		["max_level"]=9,
		["inlay_pos1"]=[[裂界回响]],
		["inlay_pos2"]=[[恶念具现]],
		["inlay_pos3"]=[[时缚诅咒]],
		["inlay_pos4"]=[[狱炎星火]],
		["inlay_pos5"]=[[圣裁余晖]], 
	},
	[8] = {
 		["key_name"]=8,
		["tab_name"]=[[衣服]],
		["can_inlay_name"]=[[衣服]],
		["equip_pos"]=0,
		["max_level"]=9,
		["inlay_pos1"]=[[炼狱魔石]],
		["inlay_pos2"]=[[暮光契约]],
		["inlay_pos3"]=[[盟约星光]],
		["inlay_pos4"]=[[双生镜像]],
		["inlay_pos5"]=[[缚能咒印]], 
	},  
}
 return config;