---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["name_arr"]={"精钢匕首","暴风之刃","暗影巨斧","制裁之刃","破军战刃",}, 
	},
	[2] = {
 		["key_name"]=2,
		["name_arr"]={"雷鸣双刃","狂暴之枪","闪电巨剑","破魔刀","无尽战刃",}, 
	},
	[3] = {
 		["key_name"]=3,
		["name_arr"]={"吸血之镰","血魂刃","末世之刃","饮血刀","破晓",}, 
	},
	[4] = {
 		["key_name"]=4,
		["name_arr"]={"护心甲","抗魔披风","反伤刺甲","不祥征兆","魔女斗篷",}, 
	},
	[5] = {
 		["key_name"]=5,
		["name_arr"]={"力量腰带","守护铠甲","霸者重装","永夜守护","贤者庇护",}, 
	},
	[6] = {
 		["key_name"]=6,
		["name_arr"]={"疾风之爪","逐风长矛","逐日之弓","影刃","纯净苍穹",}, 
	},
	["精钢匕首"] = {
 		["key_name"]=[[精钢匕首]],
		["addNumber1"]=5,
		["addNumber2"]=100,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=5000,
		["type"]=1,
		["lineType"]=1, 
	},
	["暴风之刃"] = {
 		["key_name"]=[[暴风之刃]],
		["addNumber1"]=10,
		["addNumber2"]=200,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=10000,
		["type"]=2,
		["lineType"]=1, 
	},
	["暗影巨斧"] = {
 		["key_name"]=[[暗影巨斧]],
		["addNumber1"]=15,
		["addNumber2"]=300,
		["bufftips"]=[[战斗时，20%的几率自身获得【忽视目标防御28】3%，持续8秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=20000,
		["type"]=3,
		["lineType"]=1, 
	},
	["制裁之刃"] = {
 		["key_name"]=[[制裁之刃]],
		["addNumber1"]=20,
		["addNumber2"]=500,
		["bufftips"]=[[战斗时，20%的几率自身获得【忽视目标防御28】5%，持续10秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=30000,
		["type"]=4,
		["lineType"]=1, 
	},
	["破军战刃"] = {
 		["key_name"]=[[破军战刃]],
		["addNumber1"]=30,
		["addNumber2"]=800,
		["bufftips"]=[[战斗时，20%的几率自身获得【忽视目标防御28】8%，持续15秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=50000,
		["type"]=5,
		["lineType"]=1, 
	},
	["雷鸣双刃"] = {
 		["key_name"]=[[雷鸣双刃]],
		["addNumber1"]=5,
		["addNumber2"]=1,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=5000,
		["type"]=1,
		["lineType"]=2, 
	},
	["狂暴之枪"] = {
 		["key_name"]=[[狂暴之枪]],
		["addNumber1"]=10,
		["addNumber2"]=2,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=10000,
		["type"]=2,
		["lineType"]=2, 
	},
	["闪电巨剑"] = {
 		["key_name"]=[[闪电巨剑]],
		["addNumber1"]=15,
		["addNumber2"]=3,
		["bufftips"]=[[战斗时，20%的几率自身获得【暴击伤害增加22】3%，持续8秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=20000,
		["type"]=3,
		["lineType"]=2, 
	},
	["破魔刀"] = {
 		["key_name"]=[[破魔刀]],
		["addNumber1"]=20,
		["addNumber2"]=4,
		["bufftips"]=[[战斗时，20%的几率自身获得【暴击伤害增加22】5%，持续10秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=30000,
		["type"]=4,
		["lineType"]=2, 
	},
	["无尽战刃"] = {
 		["key_name"]=[[无尽战刃]],
		["addNumber1"]=30,
		["addNumber2"]=5,
		["bufftips"]=[[战斗时，20%的几率自身获得【暴击伤害增加22】8%，持续15秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=50000,
		["type"]=5,
		["lineType"]=2, 
	},
	["吸血之镰"] = {
 		["key_name"]=[[吸血之镰]],
		["addNumber1"]=5,
		["addNumber2"]=10,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=5000,
		["type"]=1,
		["lineType"]=3, 
	},
	["血魂刃"] = {
 		["key_name"]=[[血魂刃]],
		["addNumber1"]=10,
		["addNumber2"]=20,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=10000,
		["type"]=2,
		["lineType"]=3, 
	},
	["末世之刃"] = {
 		["key_name"]=[[末世之刃]],
		["addNumber1"]=15,
		["addNumber2"]=30,
		["bufftips"]=[[战斗时，20%几率自身获得【吸血34】+1%，持续8秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=20000,
		["type"]=3,
		["lineType"]=3, 
	},
	["饮血刀"] = {
 		["key_name"]=[[饮血刀]],
		["addNumber1"]=20,
		["addNumber2"]=40,
		["bufftips"]=[[战斗时，20%几率自身获得【吸血34】+2%，持续10秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=30000,
		["type"]=4,
		["lineType"]=3, 
	},
	["破晓"] = {
 		["key_name"]=[[破晓]],
		["addNumber1"]=30,
		["addNumber2"]=50,
		["bufftips"]=[[战斗时，20%几率自身获得【吸血34】+3%，持续15秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=50000,
		["type"]=5,
		["lineType"]=3, 
	},
	["护心甲"] = {
 		["key_name"]=[[护心甲]],
		["addNumber1"]=5,
		["addNumber2"]=1,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=5000,
		["type"]=1,
		["lineType"]=4, 
	},
	["抗魔披风"] = {
 		["key_name"]=[[抗魔披风]],
		["addNumber1"]=10,
		["addNumber2"]=2,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=10000,
		["type"]=2,
		["lineType"]=4, 
	},
	["反伤刺甲"] = {
 		["key_name"]=[[反伤刺甲]],
		["addNumber1"]=15,
		["addNumber2"]=3,
		["bufftips"]=[[被攻击时，20%几率自身获得【所有伤害反弹29】+2%，持续8秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=20000,
		["type"]=3,
		["lineType"]=4, 
	},
	["不祥征兆"] = {
 		["key_name"]=[[不祥征兆]],
		["addNumber1"]=20,
		["addNumber2"]=4,
		["bufftips"]=[[被攻击时，20%几率自身获得【所有伤害反弹29】+3%，持续10秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=30000,
		["type"]=4,
		["lineType"]=4, 
	},
	["魔女斗篷"] = {
 		["key_name"]=[[魔女斗篷]],
		["addNumber1"]=30,
		["addNumber2"]=5,
		["bufftips"]=[[被攻击时，20%几率自身获得【所有伤害反弹29】+5%，持续15秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=50000,
		["type"]=5,
		["lineType"]=4, 
	},
	["力量腰带"] = {
 		["key_name"]=[[力量腰带]],
		["addNumber1"]=1,
		["addNumber2"]=5,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=5000,
		["type"]=1,
		["lineType"]=5, 
	},
	["守护铠甲"] = {
 		["key_name"]=[[守护铠甲]],
		["addNumber1"]=3,
		["addNumber2"]=10,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=10000,
		["type"]=2,
		["lineType"]=5, 
	},
	["霸者重装"] = {
 		["key_name"]=[[霸者重装]],
		["addNumber1"]=5,
		["addNumber2"]=20,
		["bufftips"]=[[自身血量低于30%时，每秒恢复最大生命值1%，持续8秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=20000,
		["type"]=3,
		["lineType"]=5, 
	},
	["永夜守护"] = {
 		["key_name"]=[[永夜守护]],
		["addNumber1"]=8,
		["addNumber2"]=30,
		["bufftips"]=[[自身血量低于30%时，每秒恢复最大生命值2%，持续10秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=30000,
		["type"]=4,
		["lineType"]=5, 
	},
	["贤者庇护"] = {
 		["key_name"]=[[贤者庇护]],
		["addNumber1"]=12,
		["addNumber2"]=50,
		["bufftips"]=[[自身血量低于30%时，每秒恢复最大生命值3%，持续15秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=50000,
		["type"]=5,
		["lineType"]=5, 
	},
	["疾风之爪"] = {
 		["key_name"]=[[疾风之爪]],
		["addNumber1"]=1,
		["addNumber2"]=1,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=5000,
		["type"]=1,
		["lineType"]=6, 
	},
	["逐风长矛"] = {
 		["key_name"]=[[逐风长矛]],
		["addNumber1"]=2,
		["addNumber2"]=2,
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=10000,
		["type"]=2,
		["lineType"]=6, 
	},
	["逐日之弓"] = {
 		["key_name"]=[[逐日之弓]],
		["addNumber1"]=3,
		["addNumber2"]=3,
		["bufftips"]=[[战斗时，20%几率自身获得【攻击伤害25】+3%，持续8秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=20000,
		["type"]=3,
		["lineType"]=6, 
	},
	["影刃"] = {
 		["key_name"]=[[影刃]],
		["addNumber1"]=4,
		["addNumber2"]=4,
		["bufftips"]=[[战斗时，20%几率自身获得【攻击伤害25】+5%，持续10秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=30000,
		["type"]=4,
		["lineType"]=6, 
	},
	["纯净苍穹"] = {
 		["key_name"]=[[纯净苍穹]],
		["addNumber1"]=5,
		["addNumber2"]=5,
		["bufftips"]=[[战斗时，20%几率自身获得【攻击伤害25】+8%，持续15秒]],
		["number_arr"]={1,0,0,},
		["itemName1"]=[[装备碎片]],
		["itemCount1"]=50000,
		["type"]=5,
		["lineType"]=6, 
	},  
}
 return config;