---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["tag_name"]=[[神话·战]],
		["tag_type"]=2,
		["target_name"]=[[圣山战盔]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"阎罗战盔",3,},}, 
	},
	[2] = {
 		["key_name"]=2,
		["tag_name"]=[[神话·战]],
		["tag_type"]=2,
		["target_name"]=[[圣山战链]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"阎罗战链",3,},}, 
	},
	[3] = {
 		["key_name"]=3,
		["tag_name"]=[[神话·战]],
		["tag_type"]=2,
		["target_name"]=[[圣山战镯]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"阎罗战镯",3,},}, 
	},
	[4] = {
 		["key_name"]=4,
		["tag_name"]=[[神话·战]],
		["tag_type"]=2,
		["target_name"]=[[圣山战戒]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"阎罗战戒",3,},}, 
	},
	[5] = {
 		["key_name"]=5,
		["tag_name"]=[[神话·战]],
		["tag_type"]=2,
		["target_name"]=[[圣山战带]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"阎罗战带",3,},}, 
	},
	[6] = {
 		["key_name"]=6,
		["tag_name"]=[[神话·战]],
		["tag_type"]=2,
		["target_name"]=[[圣山战靴]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"阎罗战靴",3,},}, 
	},
	[7] = {
 		["key_name"]=7,
		["tag_name"]=[[神话·法]],
		["tag_type"]=3,
		["target_name"]=[[冥王魔盔]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"毁灭魔盔",3,},}, 
	},
	[8] = {
 		["key_name"]=8,
		["tag_name"]=[[神话·法]],
		["tag_type"]=3,
		["target_name"]=[[冥王魔链]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"毁灭魔链",3,},}, 
	},
	[9] = {
 		["key_name"]=9,
		["tag_name"]=[[神话·法]],
		["tag_type"]=3,
		["target_name"]=[[冥王魔镯]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"毁灭魔镯",3,},}, 
	},
	[10] = {
 		["key_name"]=10,
		["tag_name"]=[[神话·法]],
		["tag_type"]=3,
		["target_name"]=[[冥王魔戒]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"毁灭魔戒",3,},}, 
	},
	[11] = {
 		["key_name"]=11,
		["tag_name"]=[[神话·法]],
		["tag_type"]=3,
		["target_name"]=[[冥王魔带]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"毁灭魔带",3,},}, 
	},
	[12] = {
 		["key_name"]=12,
		["tag_name"]=[[神话·法]],
		["tag_type"]=3,
		["target_name"]=[[冥王魔靴]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"毁灭魔靴",3,},}, 
	},
	[13] = {
 		["key_name"]=13,
		["tag_name"]=[[神话·道]],
		["tag_type"]=4,
		["target_name"]=[[如来道盔]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"避邪道盔",3,},}, 
	},
	[14] = {
 		["key_name"]=14,
		["tag_name"]=[[神话·道]],
		["tag_type"]=4,
		["target_name"]=[[如来道链]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"避邪道链",3,},}, 
	},
	[15] = {
 		["key_name"]=15,
		["tag_name"]=[[神话·道]],
		["tag_type"]=4,
		["target_name"]=[[如来道镯]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"避邪道镯",3,},}, 
	},
	[16] = {
 		["key_name"]=16,
		["tag_name"]=[[神话·道]],
		["tag_type"]=4,
		["target_name"]=[[如来道戒]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"避邪道戒",3,},}, 
	},
	[17] = {
 		["key_name"]=17,
		["tag_name"]=[[神话·道]],
		["tag_type"]=4,
		["target_name"]=[[如来道带]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"避邪道带",3,},}, 
	},
	[18] = {
 		["key_name"]=18,
		["tag_name"]=[[神话·道]],
		["tag_type"]=4,
		["target_name"]=[[如来道靴]],
		["odds"]=100,
		["need_item_list_map"]={[1]={"仙石",399,},[2]={"避邪道靴",3,},}, 
	},  
}
 return config;