---alg工作台
---xls转lua table
---本工具免费 交流QQ群:436063587
local config = {
 
	[1] = {
 		["key_name"]=1,
		["win_id"]=7,
		["btn_id"]=10004,
		["view_name"]=[[EquipTuJianOBJ]],
		["varCondition"]="$view_red_name[EquipTuJianOBJ]>1",
		["pos_x"]=6,
		["pos_y"]=10,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[2] = {
 		["key_name"]=2,
		["win_id"]=7,
		["btn_id"]=10005,
		["view_name"]=[[DemonContractOBJ]],
		["varCondition"]="$view_red_name[DemonContractOBJ]>1",
		["pos_x"]=6,
		["pos_y"]=10,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[3] = {
 		["key_name"]=3,
		["win_id"]=107,
		["btn_id"]=1000,
		["varCondition"]="$child_node_cache[1,2]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[4] = {
 		["key_name"]=4,
		["win_id"]=202,
		["btn_id"]=10001,
		["view_name"]=[[BloodlineAwakenOBJ]],
		["varCondition"]="$view_red_name[BloodlineAwakenOBJ]>1",
		["pos_x"]=6,
		["pos_y"]=10,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[5] = {
 		["key_name"]=5,
		["win_id"]=202,
		["btn_id"]=10002,
		["view_name"]=[[PulseOBJ]],
		["varCondition"]="$view_red_name[PulseOBJ]>1",
		["pos_x"]=6,
		["pos_y"]=10,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[6] = {
 		["key_name"]=6,
		["win_id"]=202,
		["btn_id"]=10004,
		["view_name"]=[[FengShuiOccultOBJ]],
		["varCondition"]="$view_red_name[FengShuiOccultOBJ]>1",
		["pos_x"]=6,
		["pos_y"]=10,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[7] = {
 		["key_name"]=7,
		["win_id"]=107,
		["btn_id"]=[[_role]],
		["varCondition"]="$child_node_cache[4,5,6]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[8] = {
 		["key_name"]=8,
		["win_id"]=102,
		["btn_id"]=[[_top_btn2_2]],
		["view_name"]=[[BerserkerPowerOBJ]],
		["varCondition"]="$view_red_name[BerserkerPowerOBJ]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[9] = {
 		["key_name"]=9,
		["win_id"]=102,
		["btn_id"]=[[_top_btn2_4]],
		["varCondition"]="$var_int[U_firstRecharge_gift]<=0",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[10] = {
 		["key_name"]=10,
		["win_id"]=102,
		["btn_id"]=[[_top_btn1_3]],
		["view_name"]=[[ActivityCenterOBJ]],
		["varCondition"]="$view_red_name[ActivityCenterOBJ]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[11] = {
 		["key_name"]=11,
		["win_id"]=102,
		["btn_id"]=[[_top_btn2_3]],
		["view_name"]=[[AllianceOrderOBJ]],
		["varCondition"]="$view_red_name[AllianceOrderOBJ]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[12] = {
 		["key_name"]=12,
		["win_id"]=102,
		["btn_id"]=[[_top_btn1_2]],
		["view_name"]=[[WelfareHallOBJ]],
		["varCondition"]="$view_red_name[WelfareHallOBJ]>1or$call_fun[WelfareHallOBJ#CheckRechargeBtnRed]=1or$call_fun[WelfareHallOBJ#CheckRechargeBtnRed2]=1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[13] = {
 		["key_name"]=13,
		["win_id"]=109,
		["btn_id"]=[[_relevel]],
		["view_name"]=[[LifeUpOBJ]],
		["varCondition"]="$view_red_name[LifeUpOBJ]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[14] = {
 		["key_name"]=14,
		["win_id"]=109,
		["btn_id"]=[[_forge]],
		["view_name"]=[[FourCellOBJ]],
		["varCondition"]="$view_red_name[FourCellOBJ]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[15] = {
 		["key_name"]=15,
		["win_id"]=102,
		["btn_id"]=[[_top_btn1_4]],
		["view_name"]=[[DailyActiveOBJ]],
		["varCondition"]="$view_red_name[DailyActiveOBJ]>1or$call_fun[DailyActiveOBJ#CheckTopBtnRed]=1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[16] = {
 		["key_name"]=16,
		["win_id"]=102,
		["btn_id"]=[[_top_btn1_5]],
		["view_name"]=[[WelfareTodayOBJ]],
		["varCondition"]="$view_red_name[WelfareTodayOBJ]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[17] = {
 		["key_name"]=17,
		["win_id"]=102,
		["btn_id"]=[[_top_btn1_6]],
		["varCondition"]="$var_int[G_cross_dfxg_state]==1or$var_int[G_cross_wxzc_state]==1or$var_int[G_cross_yyjl_state]==1or$var_int[G_cross_emgc_state]==1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[18] = {
 		["key_name"]=18,
		["win_id"]=109,
		["btn_id"]=[[_godequip]],
		["varCondition"]="$view_red_name[GodEquipOBJ]>1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},
	[19] = {
 		["key_name"]=19,
		["win_id"]=102,
		["btn_id"]=[[_top_btn1_7]],
		["view_name"]=[[CornucopiaOBJ]],
		["varCondition"]="$call_fun[CornucopiaOBJ#GetBtnRed]=1",
		["pos_x"]=-3,
		["pos_y"]=30,
		["red_type"]=0,
		["path"]=[[res/custom/red1.png]], 
	},  
}
 return config;